### ISSUE TITLE
Is "Admission" a reserved word for the mobile

### ISSUE THREAD

**Issue by michelleyee26** [apexcharts/react-apexcharts#106]
First of all, thank you for sharing your great chart!
However, during my application, I set one of the data series named "Admission", which was found missing in mobile(ipad) display, but shown successfully in the desktop. I tried to change it to "Admissions" then it worked on both platforms.
Therefore, could you give me some idea that 'Admission' is a reserved word that can't be used or it is just a bug?

Thank you very much!

**Comment by junedchhipa** [comment]
That's strange!
Can you please share a codepen demo?

**Comment by junedchhipa** [comment]
Closing as cannot reproduce.
