### ISSUE TITLE
Chart subtitle hidden at left

### ISSUE THREAD

**Issue by GustavoBlaze** [apexcharts/react-apexcharts#111]
I'm a example from project's docs: https://apexcharts.com/react-chart-demos/column-charts/basic/.
and the result is the chart with the subtitle hidden at left:
![Screenshot from 2019-11-17 12-33-00](https://user-images.githubusercontent.com/25311644/69009739-23669c80-0937-11ea-82d0-0fbf0bd3731e.png)

**Comment by junedchhipa** [comment]
If you mean the `legend` is hidden, maybe your CSS is overriding it.

Make sure you have
```javascript
legend: {
  horizontalAlign: 'center'
}
```

If the above doesn't work, you can tweak the CSS for the legend
```CSS
.apexcharts-legend {
    justify-content: center !important;
}
```
