### ISSUE TITLE
Series Data getting deleted on clicking legend for that series

### ISSUE THREAD

**Issue by UmangH-softura** [apexcharts/react-apexcharts#112]
While using the area chart with multiple series, I have encountered a bug : 

If you assign an event handler on the legend i.e the event legendClick in the option and check the series data (using console.log), the first legend that you click on will cause the data of the series associated with that particular legend will be deleted/removed even though the chart works fine at that time.

I kept a mode change where the user can view the chart even in full screen mode and it also includes a grid table under the chart which will change according to the toggling of legends on user click. However, since this data gets deleted, the data is never visible again in table. 

This happens right after the first mount of the chart, so if I exit the modal and reopen it , now the same flow gets repeated with the data missing for the first legend that was clicked (does not even show up in the chart anymore) and any legend you click now will cause the series data for that legend also to get removed as it is the first click after opening the modal.

**Comment by junedchhipa** [comment]
The series data is removed and kept in another variable to prevent calculations for a hidden series.
Hence, you may see an empty array that gets added back when you click the legend again.

You should keep the original data in a separate variable for the fullscreen mode and grid-table.
