### ISSUE TITLE
Unable to use the backgroundBarColors property in bar charts

### ISSUE THREAD

**Issue by ghost** [apexcharts/react-apexcharts#113]
Ideally this is supposed to take an array but the first color in the array just seems to be getting used across the chart

**Comment by nitish-nc** [comment]
var options = {
  chart: {
    height: 380,
    type: "bar",
    foreColor: '#6D6D6D'
  },
  plotOptions: {
    bar: {
      distributed : true,  
      colors: {
            backgroundBarColors: ['#546E7A','#000000'], 
            _**//this line above should allow me to set the background colors for the bar but only the first 
            //color seems to get picked up**_
            backgroundBarOpacity: 0.8,
        },
    }
},
  series: [
    {
      name: "Series 1",
      data: [2, 23, 19, 45, 38, 52, 45]
    }
  ],
  grid: {
     borderColor: '#6D6D6D'
  },
  xaxis: {
    categories: [
      "01 Jan",
      "02 Jan",
      "03 Jan",
      "04 Jan",
      "05 Jan",
      "06 Jan",
      "07 Jan"
    ]
  }
};

var chart = new ApexCharts(document.querySelector("#chart"), options);

chart.render();
