### ISSUE TITLE
Strange behavior for multi series line chart

### ISSUE THREAD

**Issue by wenkgps** [apexcharts/react-apexcharts#114]
Hello,
I am facing a problem :
i have multiple series to draw them in line chart with datetime xaxis
but the problem is only first series appear unless i make an action in the page like zoom in or zoom out or open inspect console. etc
once i make action other series appear and drawn on the chart
i have recorded a video for you to see the issue
[click here](https://drive.google.com/open?id=1JVIgSyAJfLdHAomvVUHDJsdeXVS3RqLM)

**Comment by ThinkSalat** [comment]
I have a similar issue with multiple series line charts in which series fail to display unless I sort them by the number of datapoints in the series. Perhaps that may help you out.
