### ISSUE TITLE
Not trim categories in Horizontal Stacked Bar Chart

### ISSUE THREAD

**Issue by pem-datahouse** [apexcharts/react-apexcharts#118]
Is there a way to either change the width of the categories section, or break line (or any way to actually see the whole category text)?

I tried rotating it, but then it was not aligned with the correspondent bars.

I created a codepen to exemplify it: https://codepen.io/jbarradas/pen/PowZpJV

**Comment by junedchhipa** [comment]
You can set `yaxis.labels.maxWidth` to avoid truncated string

```javascript
  yaxis: {
    labels: {
      show: true,
      trim: false,
      maxWidth: 240
    }
  }
```
