### ISSUE TITLE
Latest versions fail to work with samples

### ISSUE THREAD

**Issue by sergkop** [apexcharts/react-apexcharts#127]
I've tried to update the version of react-apexcharts used in samples. Up to 1.3.2 it works fine. Versions 1.3.3-1.3.5 throw an error. The reason is a slight change in the code - compare [1.3.2](https://unpkg.com/react-apexcharts@1.3.2/dist/react-apexcharts.iife.min.js) and [1.3.3](https://unpkg.com/react-apexcharts@1.3.3/dist/react-apexcharts.iife.min.js). They are identical except for `ApexCharts` replaced with `null` in the very end. Not sure why that happened.

**Comment by junedchhipa** [comment]
After debugging for hours, I found nothing. Upgraded rollup and the issue was fixed.
I will release a patch soon.
