### ISSUE TITLE
TypeError: Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by eeeman1** [apexcharts/react-apexcharts#129]
I installed first - npm install apexcharts --save

then connected to the component - import ApexCharts from 'apexcharts'

I took an example from - https://apexcharts.com/react-chart-demos/radar-charts/basic/

and got an error TypeError: Cannot read property 'document' of undefined

"apexcharts": "^3.10.0"
"react": "^16.8.6"
node v8.9.0
npm 5.5.1

**Comment by remorses** [comment]
@junedchhipa where should this be solved? `apexcharts` or `apex-charts-react`?

**Comment by pavanjn** [comment]
It worked for me by adding ssr: false to the above solution from @jsoulet 

```const Chart = loadable(() => import('react-apexcharts'), { ssr: false });```

**Comment by RezaZR** [comment]
@jsoulet it works! thank you and i think this issue should be close?

**Comment by thiendang** [comment]
> I experienced the same issue : it was due to SSR as apexcharts requires a window object during rendering.
> 
> To fix it, you can use dynamic import
> 
> ```js
> import loadable from 'loadable-components';
> const Chart = loadable(() => import('react-apexcharts'));
> ```

Hey, it worked for me. Thanks so much!!!
