### ISSUE TITLE
Multiple Y-Axis options leaves blank space when chart labels set to false

### ISSUE THREAD

**Issue by pnemi** [apexcharts/react-apexcharts#13]
Hello (it's me again),

when I use [mixed charts](https://apexcharts.com/javascript-chart-demos/mixed-charts/multiple-yaxis/) options and set y-axis labels to false, chart is still padded to right (somehow even more than before) forcing me to set negative left grid padding.

<img width="615" alt="screen shot 2018-09-07 at 07 41 12" src="https://user-images.githubusercontent.com/5919903/45200696-421cce00-b272-11e8-8077-c4e5a93b7057.png">
<img width="611" alt="screen shot 2018-09-07 at 07 41 50" src="https://user-images.githubusercontent.com/5919903/45200697-421cce00-b272-11e8-985d-9834dd0f68d3.png">

Thanks for taking a look at it :)

**Comment by junedchhipa** [comment]
Thanks for reporting @pnemi 
I agree multiple y-axis charts has some padding issues (sometimes y-axis title is cropped). I will take a look.

**Comment by junedchhipa** [comment]
@pnemi 
You can try `yaxis.floating: true` to remove the spacing.
The `floating` option takes the element out of the chart area.

**Comment by junedchhipa** [comment]
@pnemi Can we close this if the `floating` issue fixed the problem of blank space?

**Comment by pnemi** [comment]
I didn't use this solution as I'm continuing to use negative offsets.
