### ISSUE TITLE
Issue hiding a series using ApexCharts.exec() method. 

### ISSUE THREAD

**Issue by Slurpgoose** [apexcharts/react-apexcharts#134]
Hi, Im unable to hide a series using the ApexCharts.exec() method. I am able to call the updateSeries method. 

**My Goal**:
 I want to hide a series using the legend and persist hidden series after component remount.
 
I added a callback to events.legendClick
to store which series are hidden in parent state. the user selects between two components to mount in one block. if the component remounts I want to re-hide the series that the user chose to unselect.

Im sure there is a better method to achieve this then calling hideSeries after chart render. I would be happy to rethink my logic if there are any better options.

     import Chart from 'react-apexcharts';
     import ApexCharts from 'apexcharts';

 relevant section of my options

    chart: {
            type: 'bar',
            id: 'assetDistribution',
    }

inside a react class my series & categories.
my categories are passed to a function to generate chart options

    this.state = {
            series: [
                {
                name: 'Bittrex',
                data: [434, 55, 11, 22, 121, 41]
                }, 
                {
                name: 'Coinbase',
                data: [53, 32, 33, 59, 120, 22]
                }
            ],
            categories: ['BTC', 'ETH', 'NEO', 'XMR', 'NEP', 'BCH'],
    }`

my render method

    render() {
        return (
            <Chart options={this.state.options} series={this.state.series} type="bar" width={800} height={420} />
            )
    }`

//here is how Ive tried to hide series using the exec method.

    const hideSeries = () => {
       ApexCharts.exec('assetDistribution', 'hideSeries', 'Bittrex')
      //ApexCharts.exec('assetDistribution', 'hideSeries', {seriesName: 'Bittrex'})
     //ApexCharts.exec('assetDistribution', 'hideSeries', ['Bittrex'])
}

thanks in advance, any help would be greatly appreciated :)

**Comment by junedchhipa** [comment]
The methods `showSeries` and `hideSeries` were not accessible in `ApexCharts.exec` in the previous versions which have been fixed.

Please upgrade to the latest version of apexcharts (3.15.2) to get this fixed.

**Comment by Slurpgoose** [comment]
@junedchhipa thanks for the reply! I cant believe I missed this...

 In a future release would it be possible to add a check in the ApexCharts.render method to hide series using chart options.series  configuration as a default?

It seems there is a method called *addCollapsedClassToSeries* which adds  'apexcharts-series-collapsed' classname to the series which is used by legendHelpers.toggleDataSeries. 

Maybe if user can pass a classname along with a series. this className will be applied when a series is rendered. After a user toggles a series in legend it behaves as normal. if user calls chart.updateOptions(). it checks all series for classnames and makes changes to options.series accordingly. 

*example:*

     series: [
                {
                name: 'Series1',
                data: [1, 2, 3, 4],
                classNames: ['apexcharts-series-collapsed'],
               }, 
               {
                name: 'Series2',
                data: [1, 2, 3, 4],
                classNames: [],
            }
        ],
