### ISSUE TITLE
React Hooks ApexCharts.exec

### ISSUE THREAD

**Issue by thellimist** [apexcharts/react-apexcharts#136]
```
export default function ExampleChart({
  data,
  ...props
}) {
  let series = data

  useEffect(() => {
    ApexCharts.exec("example", 'updateSeries', series)  
  }, [series]);

  return (
            <Charts
              options={options}
              series={[]}
              type={"area"}
              height={300}
            />
  );
}

let options = {
   chart: { 
      id: "example",
      group: "example-groups"
   }, 
   ...
}
```

gives the error `TypeError: i.publicMethods is undefined` at line `ApexCharts.exec("example", 'updateSeries', series)`. Error is probably because I'm using it incorrectly. 

What is the correct way to update series using React Hooks?

**Comment by ahmed-rezk-dev** [comment]
Hi man,
I just stated using Apex charts, this example is working perfect to me: https://github.com/apexcharts/apexcharts.js/blob/master/samples/react/line/realtime.html

**Comment by thellimist** [comment]
@ahmed-rezk-dev that example does not use React Hooks. Let me know if you can make it work with `useEffect` or something similar.

**Comment by thellimist** [comment]
@junedchhipa do you have an example on how to use `ApexCharts.exec` with React Hooks?

**Comment by AndreasRiedel95** [comment]
Did you make ApexCharts globally available. In React write in your top level component: 
`const ApexCharts = window.ApexCharts;`

Then you can use `ApexCharts.exec` I was able to write: 

```
	useEffect(() => {
		ApexCharts.exec(
			id,
			'updateOptions',
			{
				theme: {
					palette: theme
				}
			},
			false,
			true,
			false
		);
	}, []);
```

**Comment by thellimist** [comment]
@AndreasRiedel95 in your case you are calling useEffect only once. 

```
	useEffect(() => {
		// something
	}, []); // <- sending '[]'
```

The problem occurs when an update happens by 

```
	useEffect(() => {
		// something
	}, [series]); 
```

**Comment by gfortaine** [comment]
@thellimist It looks like that it works fine : https://codesandbox.io/s/react-basic-example-7xce1

However, it seems that your example is a bit of nonsense. What is the point of updating the series by calling the method updateSeries in a useEffect Hook  ? If you update the props data in your example, the Chart will also update with the new props...

**Comment by gabrielbeauchemin** [comment]
I also don't understand the ApexCharts.exec(). From what I understand, ApexCharts is a global variable. But when in the class I import ApexChart I try to used it, I get "ApexCharts is not defined". I tried to initialize it with const ApexCharts = window.ApexCharts, but I get: property does not exist on type Window & typeof. Also, in the example that you sent gfortaine, we can see that the intellisense also say that ApexCharts is not defined.

**Comment by thellimist** [comment]
This solution works

```
...
import Charts from "react-apexcharts";
import ApexCharts from 'apexcharts';

export default function Chart({ 
  newSeries,
  newOptions,
  ...props 
}) {

  useDeepCompareEffect(() => { // or useEffect
    ApexCharts.exec(`Chart:${id}`, 'updateSeries' , newSeries);
    ApexCharts.exec(`Chart:${id}`, 'updateOptions' , newOptions, false, true, true);
  },[newSeries, newOptions]);

  return (

            <Charts
              options={newOptions}
              series={newSeries}
              type='line'
              height='350'
            />
  );
}
```

**Comment by tarun-29** [comment]
> This solution works
> 
> ```
> ...
> import Charts from "react-apexcharts";
> import ApexCharts from 'apexcharts';
> 
> export default function Chart({ 
>   newSeries,
>   newOptions,
>   ...props 
> }) {
> 
>   useDeepCompareEffect(() => { // or useEffect
>     ApexCharts.exec(`Chart:${id}`, 'updateSeries' , newSeries);
>     ApexCharts.exec(`Chart:${id}`, 'updateOptions' , newOptions, false, true, true);
>   },[newSeries, newOptions]);
> 
>   return (
> 
>             <Charts
>               options={newOptions}
>               series={newSeries}
>               type='line'
>               height='350'
>             />
>   );
> }
> ```

Can you explain it please what are these two lines in useEffect and what is ApexCharts.exec(`Chart:${id}`, 'updateOptions' , newOptions, false, true, true) false true true these arguments are for?

**Comment by tarun-29** [comment]
@thellimist can you please explain your solution i am also stuck when using ApexChart.exec method it works fine for the first time and crashes
