### ISSUE TITLE
Module not found: Can't resolve 'apexcharts/dist/apexcharts.common'

### ISSUE THREAD

**Issue by Gauthamjm007** [apexcharts/react-apexcharts#139]
Failed to compile

./node_modules/react-apexcharts/dist/react-apexcharts.min.js
Module not found: Can't resolve 'apexcharts/dist/apexcharts.common' in 'Z:\React\misc-examples\node_modules\react-apexcharts\dist'

This error occurred during the build time and cannot be dismissed.

**Comment by junedchhipa** [comment]
Which versions of apexcharts and react-apexcharts are you using?

**Comment by Gauthamjm007** [comment]
"apexcharts": {
      **"version": "3.15.3",**
      "resolved": "https://registry.npmjs.org/apexcharts/-/apexcharts-3.15.3.tgz",
      "integrity": "sha512-DfXhSqFaulF3C7YyMR77Jk4ESa66QjoqrBvxw3gLvRs5KK0fhmk0kuuWtxtpBulm2oWBVsi6VKHiy+YlBRPasg==",
      "requires": {
        "svg.draggable.js": "^2.2.2",
        "svg.easing.js": "^2.0.0",
        "svg.filter.js": "^2.0.2",
        "svg.pathmorphing.js": "^0.1.3",
        "svg.resize.js": "^1.4.3",
        "svg.select.js": "^2.1.2"
      }
    }


 "react-apexcharts": {
      **"version": "1.3.5",**
      "resolved": "https://registry.npmjs.org/react-apexcharts/-/react-apexcharts-1.3.5.tgz",
      "integrity": "sha512-I7EQvmAR0ZdJNqbMqFD0RMgP3TzNt1qViQASEei0sUrlXa47nPdlSegPg/1HD2pOXEVt9TIgHvdMEILdJ6BFPg==",
      "requires": {
        "prop-types": "^15.5.7"
      }
    }

**Comment by Gauthamjm007** [comment]
+ react-apexcharts@1.3.6
+ apexcharts@3.15.3

I UPDATED react-apexcharts to 1.3.6 and the issue is fixed now

**Comment by jhenriquevissotto** [comment]
Same bug here. Fixed nothing.

**Comment by junedchhipa** [comment]
@jhenriquevissotto Can you please tell me which react page of the website isn't working?

**Comment by hieuplasma** [comment]
npm install --save react-apexcharts apexcharts
 
i ran this comman and my problem was solved

**Comment by bennycode** [comment]
Thanks for the solution! I had "react-apexcharts" installed but forgot to install "apexcharts". 🙈

**Comment by simulanis-avish** [comment]
by this command "npm install --save react-apexcharts apexcharts"
my problem solved. thnx

**Comment by skydev0112b** [comment]
I solved above command too.
thanks.

**Comment by V1CTOR-cloud** [comment]
Resume solutions:

**Comment by marl8n** [comment]
For mi the solution was importing the library as 

```
import dynamic from 'next/dynamic'
const Chart = dynamic(() => import('react-apexcharts'), { ssr: false })
```

The error was because of using a cliente side oriented library in the server side
