### ISSUE TITLE
How to change local language dynamically?

### ISSUE THREAD

**Issue by AmeRyuuHub** [apexcharts/react-apexcharts#140]
Hello,
Please, help me to understand how to change the chart's language dynamically.
I tried to use **chart.setLocale()**, but always got error : _"...setLocale is not a function"_
In Docs I didn't find a explanetion or example, that why tried to used it with window.Apex object and  refs, but always the same error.

how to use it correctly?

Thanks in advance for your reply.

**Comment by piotr-boronczyk** [comment]
Hi, I've tried everything too. Can someone please explain this :/ After updating options object nothing seem to be happening. Even Object,assign didn't do the trick 😢

**Comment by gfortaine** [comment]
Hi,

We managed to get it right in our app. However, it looks like that **setLocale** doesn’t work very well (accessed through a ref on the component, by the way [0]). Indeed, sometimes the locale is correctly loaded, sometimes it fallbacks to the default. The only robust way that we have found is to set up **Apex.chart.defaultLocale** to the desired locale **then** to instantiate the chart only after that (thus your **return null** until a language is set).

Hope this helps,

[0] https://github.com/apexcharts/vue-apexcharts/issues/191#issuecomment-571699232

**Comment by junedchhipa** [comment]
Can you try using the `exec` function?

```javascript
ApexCharts.exec('chart-id', 'setLocale', 'en')
```

**Comment by gfortaine** [comment]
@junedchhipa tried just now. Unfortunately, it still doesn’t work well. Same problems than with trying to call **setLocale** directly (we skip the need for ref but it doesn’t work if you need to dynamically change the language only through a componentDidUpdate by example)

**Comment by junedchhipa** [comment]
Ok, can you please create a [codesandbox](https://codesandbox.io/s/6yoqonyo7r) demo so I can jump into the issue quickly?

**Comment by gfortaine** [comment]
Done ✅ :

- ApexCharts : https://codesandbox.io/s/react-basic-example-6opyx

- Apex.chart : https://codesandbox.io/s/react-basic-example-xb6uy

It looks like that only Apex.chart is working. Indeed, Apex.chart **defaultLocale** should be correctly initialized before that the Chart be instantiated with right options.

**Comment by simplecommerce** [comment]
Any update on this issue? 
I am having a similar problem with my instance, I tried `ApexCharts.exec('chart-id', 'setLocale', 'en')`, one out of X charts change.
Anyone has a working example?

**Comment by emanuelevella** [comment]
Can’t seem to make this work, tried the following:

`setLocale`, `exec`, `updateOptions` and `Apex.chart`.

Anyone has a solution?

**Comment by zzt1224** [comment]
> Can’t seem to make this work, tried the following:
> 
> `setLocale`, `exec`, `updateOptions` and `Apex.chart`.
> 
> Anyone has a solution?

```react
const const chartRef = createRef<Chart>()

const changeLocale = () => {
    chartRef.current.setLocale('en');
    chartRef.update()
}

return <Chart ref={chartRef} /> 
```

**Comment by simplecommerce** [comment]
> > Can’t seem to make this work, tried the following:
> > `setLocale`, `exec`, `updateOptions` and `Apex.chart`.
> > Anyone has a solution?
> 
> ```
> const const chartRef = createRef<Chart>()
> 
> const changeLocale = () => {
>     chartRef.current.setLocale('en');
>     chartRef.current.update()
> }
> 
> return <Chart ref={chartRef} /> 
> ```

Thanks, I had to use chartRef.current.chart.setLocale()
