### ISSUE TITLE
toggleSeries/showSeries

### ISSUE THREAD

**Issue by arjhunAtcodingmart** [apexcharts/react-apexcharts#141]
It seems that showSeries is not working fine for me, where I have used line chart with custom legend, hideSeries method is working fine, but when I use showSeries cannot able to show the line again in the chart, also tried the toggleSeries which is also hiding the line in chart not showing them again when toggling. And always returning false on toggleSeries. But working fine with the default legend

Using ApexChart.exec()

version
"apexcharts": "^3.15.2"
"react-apexcharts": "^1.3.6",

also tried 
"apexcharts": "^3.15.5"

**Comment by junedchhipa** [comment]
I would appreciate a working codesandbox example to reproduce the issue

**Comment by bn3t** [comment]
I don't know about the case of custom legend but the normal one seems to work fine: https://codesandbox.io/s/loving-resonance-x35jt?file=/src/App.js

**Comment by cdaringe** [comment]
right--i essentially desire to `series: [{ name: "some-series", data: [...], disabled: true }, ... ]` in idiomatic react fashion.

of course i could _not include_ those series up front, but then my UX suffers as they don't participate in the nice legend.
