### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by codeibrahima** [apexcharts/react-apexcharts#142]
Hello,

I'm trying to get the chart Uri by using the Data URI method. I've seen a bunch of examples using Apexchart Js to get pdf like [this CodePen from ApexChart](https://codepen.io/apexcharts/pen/JjPZPNb), when trying to reproduce it on react I got  **TypeError: Cannot read property 'type' of undefined**

Here is my component did mount look like this : 

`componentDidMount() {

    console.log(this.state.loading);
    if (this.state.loading === false) {
      const {options} = this.state;
      const node = ReactDOM.findDOMNode(this);
      if (node instanceof HTMLElement) {
        var chart = new ApexCharts(node.querySelector('.charty'), options);
        chart.render().then(() => {
          setTimeout(function() {
            chart.dataURI().then(uri => {
              console.log(uri);
            });
          }, 4000);
        });
      }
    } else {
      return;
    }
  }`

Type is defined as well in my state and in the render like so : 

`  <div>

        <div className='rfe'>
          <div className='rfea'>
            From {this.state.AxisMonth[0]} to{' '}
            {this.state.AxisMonth[this.state.AxisMonth.length - 1]}
          </div>
          <Chart
            className='charty'
            type='area'
            options={this.state.options}
            series={this.state.series}
            width='1000'
            height='380'
          />
        </div>
      </div>`

here is the error I got 

<img width="1036" alt="Capture d’écran 2020-02-07 à 08 58 15" src="https://user-images.githubusercontent.com/59965615/74015176-0961b680-4988-11ea-8efe-ce08aad8c54a.png">

I did not know if it is a problem with my code or with ApexChart.

**Comment by junedchhipa** [comment]
I have created an example on codesandbox describing how to use the dataURI function in react-apexcharts.
https://codesandbox.io/s/react-datauri-stackoverflow-60110892-iryeq

**Comment by Santoshah** [comment]
@codeibrahima would you care to share if you have figure out the solution for that issue ? I checked the above link but not helping.

**Comment by Santoshah** [comment]
I added ngif for the object and it resolved.
`<ng-container *ngIf="lineChartOptions">
                    <apx-chart 
                        [series]="lineChartOptions.series" 
                        type="line" 
                        [chart]="lineChartOptions.chart"
                        [xaxis]="lineChartOptions.xaxis" 
                        [title]="lineChartOptions.title"></apx-chart>
                </ng-container>`

**Comment by jangisaac-dev** [comment]
In my case,
If you wrote the type in both html and options objects, write it in one of the two places and test it

      <Chart
        className='charty'
        type='area'
        ---------

// var options: {
//   chart: {
//     type: 'area',

**Comment by imarks-saisudhakar** [comment]
@Santoshah Perfect solution

**Comment by itz-me-nvs** [comment]
Me too @Santoshah *ngIf="lineChartOptions" is the Perfect solution. thanks you saved my time. ( In Angular)

**Comment by mcban34** [comment]
I'm using next.js and none of what was written worked for me. The source of the error is that the options value goes undefined to the Chart component while creating the apex. The solution is very simple and it worked for me! I solved this problem with a simple options check => {
                                                                        allDetailOptions && (
                                                                            <DetailChart
                                                                                series={allDetailSeries}
                                                                                options={allDetailOptions}
                                                                            />
                                                                        )
                                                                    }

**Comment by mcban34** [comment]
I'm using next.js and none of what was written worked for me. The source of the error is that the options value goes undefined to the Chart component while creating the apex. The solution is very simple and it worked for me! I solved this problem with a simple options check => 
```
{
allDetailOptions && (
)
}
```

**Comment by mcban34** [comment]
``I'm using next.js and none of what was written worked for me. The source of the error is that the options value goes undefined to the Chart component while creating the apex. The solution is very simple and it worked for me! I solved this problem with a simple options check

 ```
{
                                                                        allDetailOptions && (
                                                                            <DetailChart
                                                                                series={allDetailSeries}
                                                                                options={allDetailOptions}
                                                                            />
                                                                        )
                                                                    }
```

**Comment by mcban34** [comment]
I'm using next.js and none of what was written worked for me. The source of the error is that the options value goes undefined to the Chart component while creating the apex. The solution is very simple and it worked for me! I solved this problem with a simple options check =>
```
 {
                    allDetailOptions && (
                                  <DetailChart
                                            series={allDetailSeries}
                                             options={allDetailOptions}
                                     />
                     )
 }
```
