### ISSUE TITLE
Updating Options with Custom Tooltip

### ISSUE THREAD

**Issue by amypaddle** [apexcharts/react-apexcharts#144]
I noticed that `updateOptions` is not being triggered when the tooltip options are updated (with custom tooltips)

In `ComponentDidMount`, `JSON.stringify` is being used to compare the previous and current options: https://github.com/apexcharts/react-apexcharts/blob/master/src/react-apexcharts.jsx#L103. `JSON.stringify` does not return anything for the `custom` property, I'm guessing the comparator is always returning true in this case and never updates the options if the tooltips change.

I'm using custom tooltips like this:
```
    tooltip: {
      shared: isTooltipShared,
      followCursor: isTooltipShared,
      custom: ({ dataPointIndex }: any) => tooltipsHTML[dataPointIndex],
    },
```
(where `tooltipsHTML` is just an array of html strings). 

Is there a way to get around this? Or can the comparator be updated?

**Comment by leonbloy** [comment]
I was caught by this one also, I changed my options object  yaxis.labels.formatter and nothing happened.

https://github.com/apexcharts/react-apexcharts/issues/144

I suspect this is a bug.

The comparison to determine if a prop (options or series) changed should not rely on JSON.stringify, that's not the React way of doing it. It should simply compare by reference. The user should be responsible of avoiding unnecessary renders by memoizing the objects.
