### ISSUE TITLE
[Question] #Zoom #RealTime: How to keep zoom after updating series?

### ISSUE THREAD

**Issue by ifisidro** [apexcharts/react-apexcharts#148]
I'm developing a page where I display in a TimeSeries chart which updates its data periodically (real time behavior). I'm setting the new data by setting its **`series` property**, as recommended  in the guides for **React**. Besides, the chart **must** have the feature of being *zoomable*. I'm facing the issue of losing the zoom (it resets itself to the default zoom) after updating the series with the new data.

Is there any way to keep the zoom the user did with the mouse before receiving new data? Even a tricky / bypass solution would be very appreciated.

Kind regards

**Comment by ifisidro** [comment]
Nobody?

**Comment by devcshort** [comment]
Hey @ifisidro 

It's been awhile since you've commented and have probably moved on by now, but since nobody else has replied I figured I'd post my solution as I ran in to this same issue just last week.

What I had to do was

1. Pass in series data as normal
2. Pass in xaxis categories as an array of strings that are in a datetime format.
3. This last part is what fixed the issue for me. xaxis type MUST be set to datetime.

```
<Chart
    type="line"
    height={340}
    width="100%"
    series={[
        {
            name: 'Example Label',
            data: seriesData
        }
    ]}
    options={{
        xaxis: {
            type: 'datetime',
            categories: seriesLabels,
            labels: {
                formatter: val => tz(val).tz('America/Los_Angeles').format('h:mma'),
            }
        }
    }}
/>
```

I hope this helps!

**Comment by kevinkga** [comment]
I've used datetime too but it keeps losing the zoomed state when the options are refreshed. do you have a fixed seriesLabels? How does that work since time is pretty much infiite @devcshort ?

**Comment by devcshort** [comment]
> I've used datetime too but it keeps losing the zoomed state when the options are refreshed. do you have a fixed seriesLabels? How does that work since time is pretty much infiite @devcshort ?

I haven't used this project in awhile, however our seriesLabels were definitely not fixed. We had a continuous flow of data refreshing in about 15 second intervals. I was fighting with this lib quite a bit, but I managed to fix the zoom issue. seriesLabels needs to be an array of strings that are in the format of datetime to properly work.
