### ISSUE TITLE
Synced charts not updating correctly

### ISSUE THREAD

**Issue by orestiskosko** [apexcharts/react-apexcharts#151]
Hi all! I have an issue while updating series and options of syncing charts. You can check the behavior on this sandbox.

https://codesandbox.io/s/dawn-grass-ylt02?fontsize=14&hidenavigation=1&theme=dark

Try changing the top select and notice that charts have the same title and the sync is not working properly.

**Comment by junedchhipa** [comment]
I see the title updates in all the charts.
Can you please make a minimal example? Without all the extra overhead updating just series and chart title?

**Comment by orestiskosko** [comment]
At first the titles are `Factor 1` and `Factor 2`. When you select another value in the dropdown, titles become `Factor 2` and `Factor 2` and stay like this for any subsequent udpate. However, the tooltips contain the correct chart title.

**Comment by Vezilic** [comment]
Hi
I have the sam issue. I just made simple example [here](https://codesandbox.io/s/syncing-charts-colors-change-problem-y0lb9) for you. Very similar to your Demo example of Syncing charts.
Thanks.

**Comment by cstrat** [comment]
I think this is all related to this bug #182 where options are overwritten.

**Comment by Vezilic** [comment]
Hi cstrat.
Thanks for your comment. 
I do not understand your solution. I do not see any way to change Syncing Charts options instead passing it as an options prop to ReactApexChart component. And I think that we can all agree that Syncing Charts component has some bug when comparing states of previous options with new ones.
It is obvious that any change on just one of Syncing Charts options overrides options on all charts in Syncing Charts group. Fortunately, only initial options when Syncing Charts component is mounted for the first time are applied correctly.
I made one workaround. Rendering Syncing Charts like they are mounted for the first time every time if any of options are changed. ☹
You can check [here](https://codesandbox.io/s/syncing-charts-colors-change-problem-forked-q9ed2) where I forked my [previous example](https://codesandbox.io/s/syncing-charts-colors-change-problem-y0lb9) in which I presented problem in simple way for contributors of this nice repo.
