### ISSUE TITLE
ES version and bundle size

### ISSUE THREAD

**Issue by flosch-hb** [apexcharts/react-apexcharts#156]
Hello,

First thank to all the contributors for this nice React integration that works perfectly fine :)

DISCLAIMER: I have imported [react-apexchart from NPM](https://www.npmjs.com/package/react-apexcharts) which I hope is this source-code?
(The package itself does not reference the GitHub repository, and this repository does not show the latest releases on NPM like v.1.3.6)

One issue for me is the bundle size.
I have a stack using among others [preact](https://preactjs.com/), [react-router](https://reacttraining.com/react-router/web/guides/quick-start), [loadable-components](https://loadable-components.com/) and [theme-ui](https://theme-ui.com/).

I use webpack 4 to build the application (just one view, a few components) and the bundled size of those dependencies (without react-apexcharts) is the following: 120.22kb (parsed) and 36.53kb (gzip).

When I install react-apexcharts and import it (I only need to display one "bar" graph:

```js
import Chart from 'react-apexcharts';
```

Then the bundle size is raised by 442.4kb (parse) or 111.61kb (gzip).
On the full application size, react-apexcharts itself takes 71.1%.

![webpack-bundle-analyzer](https://user-images.githubusercontent.com/43741708/77053269-61033100-69ce-11ea-9d90-def167665e6f.jpg)

NOTE: just noticed that one, which is probably a blocker then?
https://github.com/apexcharts/apexcharts.js/issues/567

**Comment by junedchhipa** [comment]
I recommend not to bundle the library inside your main app but load it externally via a CDN.

For react, you can load the scripts in the index.html 

```javascript
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<script src="https://cdn.jsdelivr.net/npm/react-apexcharts@1.3.6/dist/react-apexcharts.iife.min.js"></script>
```

All the [react samples](https://github.com/apexcharts/apexcharts.js/tree/master/samples/react) on the website are loaded this way.

ApexCharts doesn't support tree-shaking, hence importing only a part of the library isn't possible.
Sorry, I cannot offer any other alternative other than loading through a CDN.

**Comment by flosch-hb** [comment]
Okay, thanks for the quick confirmation :)

The CDN approach requires to also load dependencies such as react in the same fashion, I think I still prefer to use the bundle version for now, since I have internal dependencies to (p)react.

Just to give my humble opinion on https://github.com/apexcharts/apexcharts.js/issues/567, I think that splitting effort is worth it.

> I would appreciate a contribution in splitting up the modules not breaking the existing installations.

I believe this can be achieved by bundling a "full-package" plug-n-play option, composed by decoupled internal packages such as the ones you mentioned `apexcharts-core`, `apexcharts-basic`, `apexcharts-lite` etc.

I do not deny it requires some refactoring effort of course, but I believe developers would be happy to contribute, since web is becoming more and more modular those days :)

As the author of apexcharts.js, what would be your take on for instance starting a monorepo allowing to compose different subpackages (the way packages such as `babel`, `react`, `emotion` are built)?

PS: I know this may not be the best place for this discussion but since the original issue is locked, not sure where to have that?

**Comment by junedchhipa** [comment]
@flosch-hb I agree that the size of the library is a real blocker.
Monorepos would not work very well as all the modules of ApexCharts are tightly coupled. In an attempt to keep the codebase small, I created common functionalities across all the modules which resulted into tightly coupled code.

The reason I don't focus on the size issue is that there are other high priority bugs pending in the issue tracker. Also, I am not confident if splitting the codebase would be backward compatible.

**Comment by flosch-hb** [comment]
I would not expect it to be BC, but a new major version would not be a problem for anyone following normal semantic versioning ;)

I completely understand the prioritisation, and again, I was mainly asking for your take as an author, I am very glad to be able to use that library already, I do not have time expectation on any kind of delivery :)

Again, as long as you are open to it, I am pretty confident the developers community would be happy to contribute :)
A modular approach could also help understanding the codebase and how to contribute, since tightly coupled fonctionalities are usually not so easy to get into (I have not looked into apexcharts myself)

I will close this issue anyway since it cannot be helped right now, but if at some point you are interested by discussing and/or reworking the setup, do not hesitate to ping me, I would be happy to help :)
