### ISSUE TITLE
toggleSeries always return false with stacked bar chart

### ISSUE THREAD

**Issue by arjhunAtcodingmart** [apexcharts/react-apexcharts#157]
While using a line bar chart with custom legends works fine by toggleSeries but using with stacked bar chart the toggle series always returns false. Cannot able to figure out the issue

Here's the link to demo on sandbox : https://codesandbox.io/s/jovial-resonance-fc8jb

**Comment by arjhunAtcodingmart** [comment]
Think I found the issue, it's from collapsedSeries which an empty array is getting appended after hideSeries is executed in toggleSeries. empty series is appending into collapsedSeries array somewhere. @junedchhipa

**Comment by ItsWendell** [comment]
@arjhunAtcodingmart I'm trying to get this to work right now, did you find a workaround? I'm trying to manually add it back to series and then updating the chart but that doesn't work. As you said, I'm having the same issue, hiding works fine, but showing the series again from an external component doesn't.
