### ISSUE TITLE
Strange Error on Microsoft Edge

### ISSUE THREAD

**Issue by 18601673727** [apexcharts/react-apexcharts#161]
I have couple of pages with charts inside, everytime perform url hash change(ex. click links on the menu), Edge would throw
```
0: Unable to get property 'querySelector' of undefined or null reference    apexcharts.common.js (6,1)
```

Have tried all shims/shams/polyfills/browserlist/X-UA-Compatible tricks, still got same error.

Library Version: apexcharts v3.17.1
Browser Version: Microsoft Edge 44.18362
Other Version: react-dom 16.13.1 with react-router 5.1.2

Please take look into this problem, thanks in advance!

**Comment by junedchhipa** [comment]
Can you help debug this error?
Please use the un-minified version of apexcharts - https://cdn.jsdelivr.net/npm/apexcharts@3.17.1/dist/apexcharts.js

```
import ApexCharts from 'apexcharts/dist/apexcharts.js'
```

Then, please post the full error when you change the URL.

I don't have windows at the moment, so getting a full error will help to add a check where the issue is occurring.

**Comment by 18601673727** [comment]
Okay, hope this will help

![1](https://user-images.githubusercontent.com/3302620/78453181-a14afa80-76c2-11ea-971a-83a6f1de463b.PNG)
![2](https://user-images.githubusercontent.com/3302620/78453194-ae67e980-76c2-11ea-8589-9ac53471c1c1.PNG)

The menu I've talked about is entirely isolated with this `.apexcharts-menu`, I don't even know what that is..

**Comment by junedchhipa** [comment]
Thank you for sending the detailed error.
Strangely, the querySelector should not return null unless the chart was not present on the document. I;l look into it more when I get on windows.

**Comment by 18601673727** [comment]
> Thank you for sending the detailed error.
> Strangely, the querySelector should not return null unless the chart was not present on the document. I'll look into it more when I get on windows.

Yes, some pages don't have charts in, so if I switch between non-chart pages, no errors at all, so I'm guessing the error occurs during the DOM destructuring phase. Or maybe our chart events should never been bind to the document node at the first place.

**Comment by 18601673727** [comment]
Also, please take a look at my other issue on OSX by any chance. Thank you!
https://github.com/apexcharts/apexcharts.js/issues/1155

**Comment by sontek** [comment]
My users have been hitting this issue on edge as well

**Comment by sontek** [comment]
This continues to be a problem for both IE11 and Edge

**Comment by giedriusvickus** [comment]
Any news regarding this issue?
