### ISSUE TITLE
How can i change chart type at runtime on react-apexcharts?

### ISSUE THREAD

**Issue by yathomasi** [apexcharts/react-apexcharts#165]
Hello, I am trying to change the chart type dynamically at runtime.
Here is a quick link to sandbox how I am trying to implement.
[Codesandbox](https://codesandbox.io/s/apexcharts-react-demo-d6hiu
)
Here updating the series will render the new chart but the changing type doesn't.
What would be the option to force rerender the Chart DOM element on type change?

**Comment by tpiaggio** [comment]
Same question here, were you able to solve it @yathomasi ?

**Comment by yairEO** [comment]
Can somebody please assist..? I need to know also. This ain't working :/

**Comment by pavithranrocky316** [comment]
Just add key attribute, that would force a rerender and draw the chart again.

`const chartType=hasMultiple > 1 ? "line" : "bar";
<Chart key={chartType} options={options} series={series} type={chartType} />
`

**Comment by pavithranrocky316** [comment]
Just add key attribute, that would force a rerender and draw the chart again.

```javascript
const chartType=hasMultiple > 1 ? "line" : "bar";
<Chart key={chartType} options={options} series={series} type={chartType} />
```

**Comment by Rainelz** [comment]
> Just add key attribute and pass the type to it, that would force a rerender and draw the chart again as key changes dynamically.
> 
> ```js
> const chartType=hasMultiple > 1 ? "line" : "bar";
> <Chart key={chartType} options={options} series={series} type={chartType} />
> ```

This is the only solution to make the chart actually react to props after first render.
I used this approach to force an update on the w object that is passed to tooltip formatter function which don't get updated when input series change.

**Comment by tresorama** [comment]
> Just add key attribute and pass the type to it, that would force a rerender and draw the chart again as key changes dynamically.
> 
> ```js
> const chartType=hasMultiple > 1 ? "line" : "bar";
> <Chart key={chartType} options={options} series={series} type={chartType} />
> ```

This solution worked also when `options.dataLabels.formatter` function body depends on React states.
Without this trick formatter function body references to previous React state, so dataLabels won't update.

It will be good to include this `trick` inside The Documentation.

**Comment by meshalkhan2** [comment]
hy everyone...

i am using apexcharts in vuejs...
i want to update chart type when i select chart type value from v-select dropdown...
