### ISSUE TITLE
empty points in heatmap

### ISSUE THREAD

**Issue by IZUNA894** [apexcharts/react-apexcharts#169]
I am using react-apexcharts in my project ,all well good...but at time of plotting ,one problem occurred,that is ,if we have empty points in our data, that is there is no data about them,plotting with out them ,disturbed the whole graph. i tried giving values like 'null' in data object but it didn't work either.please help

**Comment by sachinkosare** [comment]
Stuck with the same problem! Were you able to find any solution for this issue?

**Comment by IZUNA894** [comment]
> Stuck with the same problem! Were you able to find any solution for this issue?

bro ..i dont remember correctly...how did i solve that problem ...but i will u my repo ...in which i had use heatmap. u can look on your own.
here:-  https://github.com/IZUNA894/DashBoard-data-Analytics

**Comment by sachinkosare** [comment]
Thanks. I see you used react-vis in your project.
I actually was able to pass the null values to the heatmap chart, just had to do some changes in the color scale range.

**Comment by IZUNA894** [comment]
ohk...hope i help u in some way
