### ISSUE TITLE
options has the wrong type

### ISSUE THREAD

**Issue by isaiahtaylorhh** [apexcharts/react-apexcharts#173]
From the `.d.ts` file:

```
options?: object
```

If you try to create a component without the `options` object, you get the error **at runtime** that `options` is marked required.

It would also be nice to have that type spelled out explicitly rather than simply `object`. It would also be nice for `series` to be spelled out rather than `Array<any>`.

**Comment by j-a-h-i-r** [comment]
The renders fine with an empty `options` object. So perhaps the runtime check can be disabled for the `option` prop?
