### ISSUE TITLE
Zoom & Pan on Horizontal Bar chart dont work

### ISSUE THREAD

**Issue by JuanDavidSolano** [apexcharts/react-apexcharts#175]
Im trying to implement zoom & pan into a Horizontal Bar chart but the zoom & pan dont work i already did it into a vertical bar chart and it worked but i cant make it work into a horizontal one
![image](https://user-images.githubusercontent.com/25392841/81618350-c4955380-93ac-11ea-9eec-5dd951ed3286.png)
 
this is the code for the chart
![image](https://user-images.githubusercontent.com/25392841/81618412-ea225d00-93ac-11ea-9ffb-22292309b948.png)

Thanks.

**Comment by nam98nd16** [comment]
Same issue here
