### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by peterchen16** [apexcharts/react-apexcharts#181]
I am trying to dynamically add data to the series of the <Chart> component of apexchart, it works fine when the series has only one or two data sets, but when there're more than 3 data sets in the series, it sometimes crashes and give the error:

apexcharts.common.js:6 Uncaught (in promise) TypeError: Cannot read property 'length' of null

there's no definitely time when it crashes, sometimes it crashes when there's 5 datas in the series, sometimes 7, sometimes 3

but when I add only the last data set to the series alone, the site works fine, so I know the data is ok

I checked all the options and series, no data is missing for apexchart to get a null

Why does this happen?

**Comment by heinnhtetzaw** [comment]
Were you able to find the cause? I'm also facing same issue now.

**Comment by fuoridallarete** [comment]
Same issue here.

**Comment by pdme** [comment]
same here

**Comment by dimitrisexeger** [comment]
Are there any updates on this issue?

**Comment by msyaifullah** [comment]
any update related to this issue?

**Comment by athirarenjan** [comment]
any solution to the above mentioned issue. i am using the apex chart version "ng-apexcharts": "^1.3.0",
