### ISSUE TITLE
How to render line chart on a fixed x-axis values ?

### ISSUE THREAD

**Issue by gauravgb21** [apexcharts/react-apexcharts#183]
I want to render multiple line charts but i want the chart to be cut off after certain xaxis value. For Example :- if there are 10 x axis values 1 - 10. I want to show data up to x = 7 but all the xaxis values should be displayed i.e from 1 - 10. 
xaxis max doesn't work that way , it doesn't display the rest of the  x-axis values , so for the above example , it shows x-axis only up to x = 7 but i want all the x-axis values i.e from 1 - 10. 
Is there any way we can achieve that ?

**Comment by iq-codechef** [comment]
@junedchhipa Can you help with this one?

**Comment by junedchhipa** [comment]
This is not achievable with ApexCharts. The chart will draw based on the `series.data` and cannot be tweaked in any other way.
