### ISSUE TITLE
Areachart indicator color not in sync with chart colors, aditionally cannot assign color to indicators.

### ISSUE THREAD

**Issue by t447** [apexcharts/react-apexcharts#184]
I have this AreaChart:
![image](https://user-images.githubusercontent.com/61561751/83939806-9da42480-a794-11ea-902f-b631f3bbbdb6.png)

This is the function I am using to generate options for it:
```javascript
const getOptions = (styles, categories) => ({
  chart: {
    toolbar: {
      show: false,
      download: false,
      selection: false,
      zoom: false,
      zoomin: false,
      zoomout: false,
      pan: false,
      autoSelected: 'pan'
    },
    type: 'area'
  },
  dataLabels: {
    enabled: styles.dataLabels || false
  },
  legend: {
    labels: {
      colors: [...styles.colors],
      useSeriesColors: false
    },
  },
  stroke: {
    show: false,
    curve: 'smooth'
  },
  fill: {
    type:'solid',
    colors: [...styles.colors],
    opacity: [0.75, 1],
  },
  xaxis: {
    type: styles.xaxisType || 'datetime',
    categories
  },
  tooltip: {
    x: {
      format: styles.xtooltipFormat || 'dd/MM/yy HH:mm'
    },
  },
});
```
I have tried changing title color, lable color, legends color, yet none of them seems to having an effect on the indicators at the bottom of the charts, I want the indicators to match the color the data is being represented in, can you please point me towards where I can find the documentation on how to change the color of these indicators? for one I don't know what they are called so I am having a really hard time finding documentation for them.

For clarity, I am outlining in red what I am talking about:
![image](https://user-images.githubusercontent.com/61561751/83939977-ea3c2f80-a795-11ea-8385-753088a9d0cc.png)

I don't know what you call these, I have been calling them indicators.

Thank you in advance! and thanks for all the work you've put in to Apexcharts!

**Comment by junedchhipa** [comment]
Those are called legends.

You should set the primary colors instead of fill.colors to allow legends to catch the colors automatically.

```javascript
const getOptions = (styles, categories) => ({
  legend: {
    ...
  },
  colors: [...styles.colors],
  fill: {
    type:'solid',
    opacity: [0.75, 1],
  }
});
```

**Comment by t447** [comment]
All right, thanks for the reply!
