### ISSUE TITLE
Grouped bar chart zero value gap issues

### ISSUE THREAD

**Issue by royallsilwallz** [apexcharts/react-apexcharts#189]
![image](https://user-images.githubusercontent.com/51167861/85829667-ddb26200-b7aa-11ea-8dd8-f2bf30e9db36.png)

I made a grouped bar chart that has some data values equivalent to zero which creates unusual gap between the bars. Is there any way to remove the gaps that has value 0 without violating the categories?

**Comment by junedchhipa** [comment]
Closing as duplicate of https://github.com/apexcharts/apexcharts.js/issues/1708
