### ISSUE TITLE
xaxis title - color setting not working

### ISSUE THREAD

**Issue by sedo226** [apexcharts/react-apexcharts#19]
`text` and `fontSize` properties working as expected, but color does not. The text element's fill is what needs to be affected. It is currently being generated as an inline style, so adding a cssClass property does not allow you to overwrite it in that way. Currently solving the issue by targeting the element after render and updating it's inline styles through javascript. 

```
xaxis: {
          title: {
            text: "Count",
            style: {
              color: "#888",
              fontSize: "14px"
            }
          }
       }
```

**Comment by junedchhipa** [comment]
Thank you for reporting. Just fixed it

**Comment by navdroid** [comment]
Same issue fontSize working but color not changing. This works for yaxis but not for xaxis.
