### ISSUE TITLE
Error "Cannot read property 'getAttribute' of null" when trying to update state from event "dataPointSelection"

### ISSUE THREAD

**Issue by akmur** [apexcharts/react-apexcharts#203]
Hello,

I have also posted this in this [apexcharts issue](https://github.com/apexcharts/apexcharts.js/issues/1813) but it is probably more suited to the `react-apexcharts` repository.

I have this problem when I want to update the series when a data point is clicked.

You can see it in this [Codesandbox](https://codesandbox.io/s/react-basic-example-106dq?file=/src/App.js)

Am I updating the state correctly, or should I do it another way?

I also tried to update my chart  using

```
ApexCharts.exec('donut', 'updateSeries', [{
    data: [40, 55, 65, 11, 23, 44, 54, 33]
}])
```

But I get the same error.

Many thanks!

**Comment by hi5on9** [comment]
Has anyone solved this problem?

**Comment by IuliiaRybets** [comment]
Yes, you need to setTimeout 
` chart: {
      events: {
        dataPointSelection: (event, chartContext, config) => 
          setTimeout(() => {smth.onClick(), 1000});
        }
      }
    },`

**Comment by mwayne16** [comment]
May not work for everyone, but was able to resolve this by wrapping options object with React.useMemo().

**Comment by fullyDeepak** [comment]
> Yes, you need to setTimeout ` chart: { events: { dataPointSelection: (event, chartContext, config) => setTimeout(() => {smth.onClick(), 1000}); } } },`

thanks this works :)
