### ISSUE TITLE
Long labels shrink line/area charts on x-axis

### ISSUE THREAD

**Issue by internationalhouseofdonald** [apexcharts/react-apexcharts#212]
When I use a long label on a smaller chart (in this case, our chart is comparing metrics between weekly breakdowns), it shrinks the chart on the x-axis. Is there any way to stop this from happening?

![Screen Shot 2020-09-10 at 6 43 07 PM](https://user-images.githubusercontent.com/20768148/92825866-a90b7b00-f395-11ea-9696-3db5738fd9ff.png)

**Comment by junedchhipa** [comment]
Sorry for the delayed response.
Is it a DateTime x-axis or a category x-axis?
You may play with font size or labels.rotate to prevent the chart from shrinking.

**Comment by internationalhouseofdonald** [comment]
It's a category x-axis. I can't really reproduce this right now without creating test data. I'll try to get a CodePen on it, but you can probably close this as a feature request.

**Comment by internationalhouseofdonald** [comment]
Do you know if changing the font size on the labels will change the appearance of the font size on the chart's annotation (or the appearance of the stroke width for that matter)?

**Comment by junedchhipa** [comment]
Changing the font size of the labels will not affect the font size of annotations.
Both are rendered differently.
