### ISSUE TITLE
Is it possible to add arrow indicator in Pie Chart

### ISSUE THREAD

**Issue by arunnjaswal** [apexcharts/react-apexcharts#219]
![Capture](https://user-images.githubusercontent.com/30898217/94652899-5bd95400-0318-11eb-94a7-77af52f4732c.PNG)

Hello Team, is it possible too add an arrow indicator, like in pic to the Apex Pie Chart. Thank you

**Comment by junedchhipa** [comment]
Sorry, this feature is not present in ApexCharts. The labels show without an arrow indicator.
