### ISSUE TITLE
Prevent Labels from being Hidden

### ISSUE THREAD

**Issue by andresumanzor** [apexcharts/react-apexcharts#22]
Hi there,

How can I prevent labels from being hidden when using `datetime` and `grid.padding.left: 0` & `grid.padding.right: 0`?

Thanks,
Andres

![screen shot 2018-10-23 at 1 25 04 pm](https://user-images.githubusercontent.com/20602109/47385416-2e64e400-d6c7-11e8-8084-a53ed37d6140.png)

**Comment by andresumanzor** [comment]
7:00 and 23:00 is partially hidden (as seen on the pic)

**Comment by junedchhipa** [comment]
This is the default behavior.
I check if the first labels exceed the grid's left position and the last label exceeds the grid's right position, then I hide it.
Although the first label shouldn't be hidden here, there is ample space to print it.

I will do some more checks

**Comment by andresumanzor** [comment]
Hi there @junedchhipa,

Thanks for your fast reply!

Is there any way I can override this checks in order for it to print the labels anyways?

Cheers,
Andres

**Comment by andresumanzor** [comment]
I did double check on my end and not even making the graph's wider fixes it so, please do let me know if there is anything I can do on my end for it to make the labels to display

**Comment by junedchhipa** [comment]
I will release a minor update tomorrow in which I will give an option to unhide these hidden labels.
Thanks for your patience

**Comment by andresumanzor** [comment]
Thank you so much @junedchhipa, please do let me know through here once it is released!

**Comment by junedchhipa** [comment]
Can you please create a codepen demo so I can easily reproduce this issue on my end?

**Comment by andresumanzor** [comment]
Sorry for my late reply and sure, here it is: https://codesandbox.io/s/6nw3ol5k7z

**Comment by andresumanzor** [comment]
Sorry for my late reply and sure, here it is: https://codesandbox.io/s/6nw3ol5k7z @junedchhipa
