### ISSUE TITLE
Display markers even if there is only one data set for each serie.

### ISSUE THREAD

**Issue by andresumanzor** [apexcharts/react-apexcharts#23]
Hi there @junedchhipa, hope you are doing amazing!

How can I achieve this:

![image](https://user-images.githubusercontent.com/20602109/47576563-057c6300-d902-11e8-81b4-8f21fe99b1c5.png)

If there is only one entry on each of the series' `data` array?

Here is a CodeSandbox which can be used as a reference: https://codesandbox.io/s/oqn6y4yj99.

Thank you,
Andres

**Comment by junedchhipa** [comment]
So, it doesn't work if there is just 1 dataPoint, right?
This is a bug and needs to be tested. Thanks for reporting.

**Comment by andresumanzor** [comment]
Hi there @junedchhipa,

Thanks for your reply and you are correct, it only happens when the series contains only one dataPoint and, did notice that if you add a second dataPoint into the series then, the series are displayed as on the image I shared with you above.

Please do let me know if you have any updates regarding this issue.

Thanks!

**Comment by junedchhipa** [comment]
Ok, thanks for the response. I will look into it soon.

**Comment by junedchhipa** [comment]
Fixed it. Will be shipped with release 2.2.0
