### ISSUE TITLE
Chart Type is missing treemap

### ISSUE THREAD

**Issue by lucafaggianelli** [apexcharts/react-apexcharts#232]
I'm using ApexCharts with React and Typescript, but the `<Chart>` component `type` property is missing the `"treemap"`  type

**Comment by junedchhipa** [comment]
Thanks for letting me know.
A new version will be published soon.

**Comment by barsh11** [comment]
Hi, I saw there is a fix to this issue.
I tried copying the fix into my node modules folder but I can't make this work.
How should I use the fix in my application? I still see this type error.
