### ISSUE TITLE
incorrect colors with one group

### ISSUE THREAD

**Issue by evless** [apexcharts/react-apexcharts#235]
I came across problem in linecharts when I used graphs with one group for sync. If I add one more graph I will get incorrect colors in every graph. If I do dynamic key for graphs it will work correct, but I think it's very bad decision. I did live example: https://codesandbox.io/s/react-update-example-forked-u46ic

**Comment by youhackme** [comment]
Same issue here. What do you mean by doing "dynamic key" to get it working? I'm so desperate to have a quick solution even if not the best decision. :)

**Comment by nekitk** [comment]
> Same issue here. What do you mean by doing "dynamic key" to get it working? I'm so desperate to have a quick solution even if not the best decision. :)

Put `key={Math.random()}` on each graph so they will fully rerender when graphs list update. Downside is that they will fully rerender loosing zoom state and replaying mount animation.
