### ISSUE TITLE
Cannot read property 'getPreviousPaths' of null

### ISSUE THREAD

**Issue by evless** [apexcharts/react-apexcharts#236]
Maybe it's problem connects with #235 If I try remove graph I will get error about getPreviousPaths

Example: https://codesandbox.io/s/react-update-example-forked-u46ic

Video: http://s.csssr.ru/U7RQKLD4J/2020-11-10-15-11-36-7gxvj.mp4

**Comment by superslau** [comment]
@evless I had similar issue, i forked the library with a potential fix in my fork. I experienced it mainly with linked charts, when navigating away and back to the page.

**Comment by Soviut** [comment]
@superslau could you please link to your fork?

**Comment by mpsijben** [comment]
I have the same issue, How did you fix it? The problems seems as well with linked charts

**Comment by superslau** [comment]
Hey @Soviut & @mpsijben it's been a while and i don't use apexcharts any more but here's what I have

https://github.com/superslau/react-apexcharts/commit/94bbdc947d20ead9a9da380c79ee9dd8ef0859fe
