### ISSUE TITLE
Is it possible to change the color of the piechart border and segment border colors

### ISSUE THREAD

**Issue by Salmonlegs** [apexcharts/react-apexcharts#237]
Hi there team,

Is it possible to change the color of the piechart border and segment border colors as indicated in the screenshot?

Thanks 👍 
<img width="941" alt="Screen Shot 2020-11-16 at 11 09 33 am" src="https://user-images.githubusercontent.com/42637917/99208760-6a15fd80-27fc-11eb-9073-0959707c4384.png">

**Comment by junedchhipa** [comment]
Sorry, both the colors represent the same path so it's not possible to give a different color.

**Comment by Salmonlegs** [comment]
Hey @junedchhipa, sorry if I wasn't clear. I'm just trying to change the color of the one path (e.g. change the current white border/segment border from white to grey), I just haven't been able to figure it out if it is possible.

Thanks again.

**Comment by junedchhipa** [comment]
Use `stroke.colors` 

```js
var options = {
  series: [44, 55, 13, 43, 22],
  chart: {
    type: 'pie'
  },
  stroke: {
    colors: ['#666']
  }
}
```
