### ISSUE TITLE
TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by Holenvik** [apexcharts/react-apexcharts#238]
Hi, I have a problem
All props are good as you can see, but Apexchart is crashing every time
Installed last versions of react-apexcharts and apexcharts

**Comment by Holenvik** [comment]
![Безымянный222](https://user-images.githubusercontent.com/38699425/99592924-ecbbda00-2a01-11eb-9183-fe64ff05c55e.png)

**Comment by Holenvik** [comment]
![Безымянный222](https://user-images.githubusercontent.com/38699425/99593005-09f0a880-2a02-11eb-8e3e-dece3c831946.png)

**Comment by Holenvik** [comment]
xaxis categories can be only only [] or string[]
series: [] | {  name: string;
    data: number[]}[]

**Comment by Holenvik** [comment]
<ApexCharts
                    options={{
                        chart: {
                            locales: [APEX_CHART_LOCALE_DATA],
                            defaultLocale: 'ru',
                            type: 'bar',
                            height: 350,
                            stacked: true,
                        },
                        plotOptions: {
                            bar: {
                                horizontal: true,
                            },
                        },
                        fill: {
                            opacity: 1,
                        },
                        stroke: {
                            width: 1,
                            colors: ['#fff'],
                        },
                        legend: {
                            position: 'bottom',
                        },
                        responsive: [
                            {
                                breakpoint: 480,
                                options: {
                                    legend: {
                                        position: 'bottom',
                                        offsetX: -10,
                                        offsetY: 0,
                                    },
                                },
                            },
                        ],
                        yaxis: {
                            labels: {
                                formatter: (value: string) =>
                                    getMonthAsText(value),
                            },
                        },
                        xaxis: {
                            categories,
                        },
                    }}
                    series={prices}
                    type="bar"
                    height={460}
                    width={'100%'}
                />

**Comment by sleleko** [comment]
Привет! Как решил в итоге? и на какой конкретно версии это вылезло? У меня тоже самое на 3.23.1

**Comment by Moumit** [comment]
Any fix on this? facing the same issue

**Comment by AyemunHossain** [comment]
Facing the same issue still ....
