### ISSUE TITLE
Piechart border and segment border colors

### ISSUE THREAD

**Issue by Salmonlegs** [apexcharts/react-apexcharts#239]
Hi @junedchhipa,

I've attached the question you responded to and tried to reply but I don't think you got it.

As you highlighted in your response, both colors (border and segment border) represent the same path and therefore they cannot be different colors but this is not what I am trying to accomplish. I would just like to change the color of the one path (e.g. border & segment border #999999).
Is this possible?

Cheers for the awesome charts  👍 

<img width="924" alt="Screen Shot 2020-11-19 at 7 42 37 am" src="https://user-images.githubusercontent.com/42637917/99602423-683a7d00-2a3c-11eb-80af-305e2cd6299f.png">

**Comment by junedchhipa** [comment]
Use `stroke.colors` array

```js
var options = {
  series: [44, 55, 13, 43, 22],
  chart: {
    type: 'pie'
  },
  stroke: {
    colors: ['#666']
  }
}
```
