### ISSUE TITLE
Prevent charts from auto-generating labels when setting the xaxis.type on "datetime"

### ISSUE THREAD

**Issue by andresumanzor** [apexcharts/react-apexcharts#24]
Hi there @junedchhipa,

How can I prevent this:
![image](https://user-images.githubusercontent.com/20602109/47656462-bbd78680-db54-11e8-8b0c-aadc03111fcf.png)

From happening if there are few data entries while the `xaxis.type` attribute is set on `"datetime"`?

On this example, only `2018-10-29T07:00:00.000Z` and `2018-10-29T08:00:00.000Z` are present as datapoints.

Thank you,
Andres

**Comment by junedchhipa** [comment]
Hi @andresumanzor 
Do you mean - if there are fewer data-points, the number of ticks should be less than what is generated?

**Comment by junedchhipa** [comment]
You can try [customFormatter](https://apexcharts.com/docs/options/xaxis/#formatter) for generating a fixed number of x-axis labels.

A full example of this - https://apexcharts.com/javascript-chart-demos/area-charts/irregular-timeseries/

Make sure to set xaxis.tickAmount to some smaller value.

```javascript
xaxis: {
  type: 'datetime',
  tickAmount: 8,
  labels: {
      formatter: function(val, timestamp) {
        return moment(new Date(timestamp)).format("HH:mm")
    }
  }
}
```

**Comment by andresumanzor** [comment]
Thanks, it worked! 👍
