### ISSUE TITLE
Weird white lines on Line chart and missing icons

### ISSUE THREAD

**Issue by alexdemartos** [apexcharts/react-apexcharts#245]
Hi, any idea why my chart looks like this?

I guess the white portions below/above the series lines should not appear.

![Captura](https://user-images.githubusercontent.com/2833410/103412669-9d2b0b00-4b76-11eb-8931-183eab3e6a4c.PNG)

`
stroke: {
            curve: 'stepline',
            dashArray: [0, 8],
            width: [4, 1]
}, ...
`

xaxis is of type 'datetime'

Thanks in advance!

**Comment by junedchhipa** [comment]
Are you using any custom SVG CSS?
As your toolbar icons are also white, I suspect some CSS rules are being overwritten.

**Comment by alexdemartos** [comment]
You are very right sir! I had one CSS rule that was messing the graph up. Sorry and thank you very much :)
