### ISSUE TITLE
How to add "scrollbar" to "react-apexcharts"?

### ISSUE THREAD

**Issue by yuvalr55** [apexcharts/react-apexcharts#246]
import :
```
import Chart from 'react-apexcharts'
```

I added this code in "options":
```
  scrollbar: {
                    enabled: true
                },
```

And this code too

```
  yAxis: {
                    categories: this.props.series.map(data=>data.name),
                    title: null,
                    min: 0,
                    max: 5,
                    scrollbar: {
                        enabled: true
                    }
                }
```
And the "scrollbar" is not added.

jsx:
```
  <Chart options={this.state.options} highcharts={Highcharts} series={this.state.series} type="heatmap" width="100%" height={70+this.state.series.length*35} />

```

![Screenshot_2](https://user-images.githubusercontent.com/59453585/103415977-2cdbb400-4b8d-11eb-8ef6-696afd3c8de1.jpg)

**Comment by junedchhipa** [comment]
Sorry, this feature is not available in ApexCharts.

**Comment by Huzaif-Ahmed** [comment]
hi

i am facing an issue with graph not being rendered neither my browser nor my console gives the error


`const dates = ["Mon Jan 16 2017","Tue Jan 17 2017","Wed Jan 18 2017","Thu Jan 19 2017","Fri Jan 20 2017","Sat Jan 21 2017","Sun Jan 22 2017","Mon Jan 23 2017","Tue Jan 24 2017","Wed Jan 25 2017","Thu Jan 26 2017","Fri Jan 27 2017","Sat Jan 28 2017","Sun Jan 29 2017","Mon Jan 30 2017","Tue Jan 31 2017","Wed Feb 01 2017","Thu Feb 02 2017","Fri Feb 03 2017","Sat Feb 04 2017","Sun Feb 05 2017","Mon Feb 06 2017","Tue Feb 07 2017","Wed Feb 08 2017","Thu Feb 09 2017","Fri Feb 10 2017","Sat Feb 11 2017","Sun Feb 12 2017","Mon Feb 13 2017","Tue Feb 14 2017","Wed Feb 15 2017","Thu Feb 16 2017","Fri Feb 17 2017","Sat Feb 18 2017","Sun Feb 19 2017","Mon Feb 20 2017","Tue Feb 21 2017","Wed Feb 22 2017","Thu Feb 23 2017","Fri Feb 24 2017","Sat Feb 25 2017","Sun Feb 26 2017","Mon Feb 27 2017","Tue Feb 28 2017","Wed Mar 01 2017","Thu Mar 02 2017","Fri Mar 03 2017","Sat Mar 04 2017","Sun Mar 05 2017","Mon Mar 06 2017","Tue Mar 07 2017","Wed Mar 08 2017","Thu Mar 09 2017","Fri Mar 10 2017","Sat Mar 11 2017","Sun Mar 12 2017","Mon Mar 13 2017","Tue Mar 14 2017","Wed Mar 15 2017","Thu Mar 16 2017","Fri Mar 17 2017","Sat Mar 18 2017","Sun Mar 19 2017","Mon Mar 20 2017","Tue Mar 21 2017","Wed Mar 22 2017","Thu Mar 23 2017","Fri Mar 24 2017","Sat Mar 25 2017","Sun Mar 26 2017","Mon Mar 27 2017","Tue Mar 28 2017","Wed Mar 29 2017","Thu Mar 30 2017","Fri Mar 31 2017","Sat Apr 01 2017","Sun Apr 02 2017","Mon Apr 03 2017","Tue Apr 04 2017","Wed Apr 05 2017","Thu Apr 06 2017","Fri Apr 07 2017","Sat Apr 08 2017","Sun Apr 09 2017","Mon Apr 10 2017","Tue Apr 11 2017","Wed Apr 12 2017","Thu Apr 13 2017","Fri Apr 14 2017","Sat Apr 15 2017","Sun Apr 16 2017","Mon Apr 17 2017","Tue Apr 18 2017","Wed Apr 19 2017","Thu Apr 20 2017","Fri Apr 21 2017","Sat Apr 22 2017","Sun Apr 23 2017","Mon Apr 24 2017","Tue Apr 25 2017","Wed Apr 26 2017","Thu Apr 27 2017","Fri Apr 28 2017","Sat Apr 29 2017","Sun Apr 30 2017","Mon May 01 2017","Tue May 02 2017","Wed May 03 2017","Thu May 04 2017","Fri May 05 2017","Sat May 06 2017","Sun May 07 2017","Mon May 08 2017","Tue May 09 2017","Wed May 10 2017","Thu May 11 2017","Fri May 12 2017","Sat May 13 2017","Sun May 14 2017","Mon May 15 2017"
    ]

    const Price=[15,160379978,170493749,160785250,167391904,161576838,161413854,152177211,140762210,144381072,154352310,165531790,175748881,187064037,197520685,210176418,196122924,207337480,200258882,186829538,192456897,204299711,192759017,203596183,208107346,196359852,192570783,177967768,190632803,203725316,218226177,210698669,217640656,216142362,201410971,196704289,190436945,178891686,171613962,157579773,158677098,147129977,151561876,151627421,143543872,136581057,135560715,122625263,112091484,98810329,99882912,94943095,104875743,116383678,125028841,123967310,133167029,128577263,115836969,119264529,109363374,113985628,114650999,110866108,96473454,104075886,103568384,101534883,115825447,126133916,116502109,130169411,124296886,126347399,131483669,142811333,129675396,115514483,117630630,122340239,132349091,125613305,135592466,123408762,111991454,116123955,112817214,113029590,108753398,99383763,100151737,94985209,82913669,78748268,63829135,78694727,80868994,93799013,99042416,97298692,83353499,71248129,75253744,68976648,71002284,75052401,83894030,90236528,99739114,96407136,108323177,101578914,115877608,112088857,112071353,101790062,115003761,120457727,118253926,117956992]
      
    const series = [{
        name: 'XYZ MOTORS',
        data: dates.map((date, index) => {
          return { x: dates, y: Price[index] };
        })
     }];
    
     const options = {
        chart: {
          type: 'area',
          height: 350,
          zoom: {
            enabled: true,
            type: 'x',
            autoScaleYaxis: true
          },
          toolbar: {
            autoSelected: 'zoom'
          }
        },
        dataLabels: {
          enabled: false
        },
        markers: {
          size: 0,
        },
        title: {
          text: 'Stock Price Movement',
          align: 'left'
        },
        fill: {
          type: 'gradient',
          gradient: {
            shadeIntensity: 1,
            inverseColors: false,
            opacityFrom: 0.5,
            opacityTo: 0,
            stops: [0, 90, 100]
          },
        },
        yaxis: {
          labels: {
            formatter: function (val) {
              return (val / 1000000).toFixed(0);
            },
          },
          title: {
            text: 'Price'
          },
          
        },
        xaxis: {
          type: 'datetime',
        },
        tooltip: {
          shared: false,
          y: {
            formatter: function (val) {
              return (val / 1000000).toFixed(0);
            }
          }
        }
     };
    return (
        <div>
            <ApexChart type="line" options={options} series={series} height={400} width={900} />
        </div>
    )`

![image](https://github.com/apexcharts/react-apexcharts/assets/104403864/9e41b00d-f311-4f19-a5de-60ae3adfece6)
