### ISSUE TITLE
autoScaleYaxis on zoom inside Candlestick chart doesn't behave properly

### ISSUE THREAD

**Issue by jovan6jovan** [apexcharts/react-apexcharts#254]
=== **So this is how the graph looks initially, everything is okay.** ===

![candlestick-chart-autoscaleyaxis-zoom](https://user-images.githubusercontent.com/30269157/104656394-811f8180-56bf-11eb-805f-753272a1078d.png)

But then when I zoom it, the Y axis scales strangely. It tries to center everything, giving me bigger max and smaller min values than I **actually** have in my data.
E.g. when I zoom it, I would like to have a max value of 9350 (not 10221.7) and a min value of let's say 9100 (not 8322.3). 

![candlestick-chart-autoscaleyaxis-zoom-2](https://user-images.githubusercontent.com/30269157/104656417-8d0b4380-56bf-11eb-8be0-4e1429f1d7ec.png)

Can you tell me how can I achieve this? I tried to set max and min values on the y axis, but that's not the solution for this problem.
Zoom is enabled only on X axis, and autoScaleYaxis is set to true.

**Comment by tchin8** [comment]
I am also facing this issue and have been empty handed in figuring out a solution.

**Comment by mr-smit** [comment]
same problem, no solution

**Comment by seongjae0325** [comment]
It works well :) Thanks for sharing your solution
