### ISSUE TITLE
Donut chart  - padding between series items in plot 

### ISSUE THREAD

**Issue by qualle-admin** [apexcharts/react-apexcharts#259]
![chart-comparison](https://user-images.githubusercontent.com/65623969/106515427-871cad00-648a-11eb-999e-1bbf21210d6c.png)

Hello, I am unaware of an existing configuration which would produce the desired result shown above, is it possible with the options object or with css?

**Comment by MerApelsin** [comment]
You can use the `stroke` property for that;

```
stroke: {
      show: false // To have no space between em
      colors: ["#000"] // if you want space but other color(s), make the borders black
    },
```
Documentation for it can be found here: https://apexcharts.com/docs/options/stroke/
Hope it helps :)

**Comment by kaynetpc** [comment]
using ApexChart with react and Am getting this error "Unhandled Rejection (TypeError): e is null" 
it do pop up ocationallay and break the system please anyone help..

![erro](https://user-images.githubusercontent.com/52090858/107163018-6632eb00-69a7-11eb-87ce-1702f3d096b8.PNG)

**Comment by kaynetpc** [comment]
import React from 'react';
import Chart from 'react-apexcharts';


function ZoneDonut({label = ["Male", "Female"], data = []}) {
   const options = {
        labels: label,
        legend:{ 
            position: 'bottom'
        },
        dataLabels: {
            enabled: true
        }
    };
    const series = [2, 10]
    return (
        <div>
            <Chart options={options} series={series} width="100%"  type="donut" />
        </div>
    )
}

export default ZoneDonut

**Comment by daniel-ilan** [comment]
This does not solve the issue if the background is a pattern - it should be able to be transparent and still add padding
