### ISSUE TITLE
Donut Title

### ISSUE THREAD

**Issue by DamickDoni** [apexcharts/react-apexcharts#26]
Hi,

How it is possible to change the center text in a Donut Chart? I tried it with PlotOptions, Datalabels, and Tooltip. 

How can I get the element that is printed in the center (when I hover a pieSlice)? 

What I want to achieve: I want to init the Donut with an empty space in the center (nothing should be shown). When I hover a pieSlice, I want to show an Image.

My actual options and series:
```
    const series = [44, 55, 41, 17, 15];
    const options = {
      labels: ['a', 'b', 'c', 'd', 'e'],
      legend: {
        show: true,
        showForSingleSeries: true,
        position: 'bottom',
        horizontalAlign: 'center',
        verticalAlign: 'middle',
        floating: false,
        fontSize: '14px',
        textAnchor: 'start',
        useSeriesColors: false,
      },
      onItemClick: {
        toggleDataSeries: true,
      },
      onItemHover: {
        highlightDataSeries: true,
      },
      dataLabels: {
        enabled: true,
      },
      theme: {
        monochrome: {
          enabled: true,
          color: '#00e2b8',
          shadeTo: 'dark',
          shadeIntensity: 0.8,
        },
      },
    };
```

**Comment by junedchhipa** [comment]
You can change the text of donut-labels in `plotOptions.pie.donut.labels`
https://apexcharts.com/docs/options/plotoptions/pie/#labels

But, you cannot place an image inside donut when user hovers over a particular slice. Currently, that is not possible.

**Comment by DamickDoni** [comment]
maybe I can do it and you can handle it like an enhancement :-) But thanks I will check the plotOptions

**Comment by OlgaDorofeeva** [comment]
> You can change the text of donut-labels in `plotOptions.pie.donut.labels`
> https://apexcharts.com/docs/options/plotoptions/pie/#labels
> 
> But, you cannot place an image inside donut when user hovers over a particular slice. Currently, that is not possible.

Hello, can I place an image inside donuts now?
