### ISSUE TITLE
How to plot dynamic yaxis against static datetime xaxis

### ISSUE THREAD

**Issue by j0flintking02** [apexcharts/react-apexcharts#263]
I am creating a graph to display today's data and yesterday's data stacked. What am trying to achieve is to plot the chart with yesterday's data dimed and the red dashed line as the demarcation
<img width="660" alt="Screen Shot 2021-02-16 at 12 16 26" src="https://user-images.githubusercontent.com/26383328/108049408-e369fa00-7050-11eb-8b49-c641c620f648.png">

**Comment by Faizan-ah** [comment]
I also have a similar problem. I am using a candlestick graph to view OHLC. But the y axis remains fixed when I zoom.
