### ISSUE TITLE
How to adjust the step of xaxis with a large array

### ISSUE THREAD

**Issue by XiyuYoyoChen** [apexcharts/react-apexcharts#264]
**Description**
I am looking for a way to adjust the step of the x-axis. I have a large array with length greater than 500. Instead of applying every single element in the array to the x-axis.

For example `const myStringArray = ["00:00", "00:01", ......., "10:00"]`, instead of having all the elements in the array on the x-axis label, how do I apply a step to skip through some of the x-axis label?

I am currently having something basic such as 
```js
const myStringArray = ["00:00", "00:01", ......., "10:00"];
const options = { 
  // other properties
  xaxis: {
    categories: myStringArray,
  }
}
```
**Current Result**
Currently I have the result as:
![Screen Shot 2021-02-18 at 12 20 14 PM](https://user-images.githubusercontent.com/27474578/108416514-a97d2d00-71e3-11eb-936a-b36fbd73e0b1.png)

**Goal**
I'm trying to accomplish a result as:
![Screen Shot 2021-02-18 at 12 20 56 PM](https://user-images.githubusercontent.com/27474578/108416585-c285de00-71e3-11eb-9e4b-7c0ff8d25cf5.png)

**Additional Description**
The array I have above is just to elaborate as an example. In real code, I extract the values in the array by making a network request. The x-axis's unit is based on the timestamp of a video converted into `"mm:ss"`. I have tried dividing the total time and apply to the xaxis label, but each of the timestamp value in the array has its corresponding y-value, when I divide the x-axis, the label and the corresponding y-value does not match.

**Comment by XiyuYoyoChen** [comment]
I figured it out by adding a `tickAmount` property in the option configuration. It will divide by the number being passed in.

**Comment by rot0505** [comment]
@XiyuChen-95 `tickAmount` is not working if the x-axis values are datetime
