### ISSUE TITLE
Marker colors are wrong

### ISSUE THREAD

**Issue by lior-fortifieddata** [apexcharts/react-apexcharts#268]
Please see below: looks like a bug, but I hope it's only wrong configuration:

The marker of the green line is blue, and the one of the blue line is green

https://codesandbox.io/s/react-basic-example-forked-x9gyd?file=/src/App.js

**with latest version: (3.25)**

![image](https://user-images.githubusercontent.com/59799643/109483122-85450a00-7a87-11eb-87ec-b02adf50aced.png)

**with version 3.19.3 its fine**

![image](https://user-images.githubusercontent.com/59799643/109482734-0a7bef00-7a87-11eb-8481-8c1358fc9d38.png)

**Comment by acarmona1989** [comment]
I upgraded the version to 3.25, but the bug exist yet. This bug can be reproduced if we change the chart type to bar of the second series. In that way the marker for the first series will color with the second series color.

https://codesandbox.io/s/react-basic-example-forked-c4fxr?file=/src/App.js
