### ISSUE TITLE
Update only path nodes when update data series

### ISSUE THREAD

**Issue by luq10** [apexcharts/react-apexcharts#271]
As I see react-apexcharts rerenders whole svg element when I update data series. 

Demo: [codesandbox](https://codesandbox.io/s/apexchart-xbhrl)

When I open this demo and elements tab in web console I see that generated `div` with `svg` element is blinking when I click Update button - so this means that whole `svg` element is recreated.

In this case I need only rerenders `path` elements with representing series data. This demo code is not optimal when I want to updating my data very fast. So my question is - this is how react-apexcharts / apexcharts works or mayby I'm doing something wrong?

**Comment by hanupratap** [comment]
Hey, did you find any solution ?

**Comment by luq10** [comment]
@hanupratap Unfortunately no, but I ask the same question in base apexcharts here - https://github.com/apexcharts/apexcharts.js/issues/2316 you can track this issue.
