### ISSUE TITLE
Newer versions with bugfixes not released?

### ISSUE THREAD

**Issue by bmike7** [apexcharts/react-apexcharts#276]
In our project we're dealing with a problem that "treemap" is missing from chart type. So it's related to following issue:

https://github.com/apexcharts/react-apexcharts/issues/232

The issue is closed and I see it is added but we still have the problem. According to our package.json file we are using version "react-apexcharts": "^1.3.7" . But it seems that the latest released version is v1.1.0 (https://github.com/apexcharts/react-apexcharts/releases)

Could it be that actual released version is an older one than v1.3.7?

(In our project, the file node_modules/react-apexcharts/types/react-apexcharts.d.ts looks exactly like the one in the dist folder: https://github.com/apexcharts/react-apexcharts/blob/master/dist/react-apexcharts.d.ts)

**Comment by junedchhipa** [comment]
Released react-apexcharts@1.3.8
Sorry for the delay
