### ISSUE TITLE
Labels in Donut Chart to show Name not Value

### ISSUE THREAD

**Issue by DamickDoni** [apexcharts/react-apexcharts#28]
Hi,

as the headline says. Is it possible to show the Name and not the Value in the Donut Chart?
At the moment I have a series with [50, 50] and labels with [Series1, Series2]. The Donut shows me 50% and 50% in the Donut. But I want to show Series 1 and Series 2 in the segment in the Donut. 

Any options to do that?

**Comment by DamickDoni** [comment]
nvm found a solution
use data labels and insert a custom formater

**Comment by junedchhipa** [comment]
```javascript
dataLabels: {
    formatter: function(val, opts) {
        return opts.w.globals.seriesNames[opts.seriesIndex]
    }
}
```

For anyone seeking a similar solution.
