### ISSUE TITLE
App is not compiling with 1.3.8

### ISSUE THREAD

**Issue by nikup** [apexcharts/react-apexcharts#285]
We get the following error when upgrading to 1.3.8
`JSX element type 'ReactApexChart' does not have any construct or call signatures.`

where ReactApexChart comes from 
`import ReactApexChart from 'react-apexcharts';`

I believe the default export type was removed with this version and I don't see a new way to call the chart, are we missing something?

**Comment by ThaDeveloper** [comment]
I'm also facing the same, tried updating `@types/react` but didn't resolve.

**Comment by junedchhipa** [comment]
Hey, thanks for raising the issue. It's a major one. I am releasing a new version asap.

**Comment by junedchhipa** [comment]
I released react-apexcharts@1.3.9
There was an issue with the typescript file.

Can you please test with the latest version and report if it fixes the issue?
