### ISSUE TITLE
Keeping the zoom level after updating the data

### ISSUE THREAD

**Issue by SWi98** [apexcharts/react-apexcharts#286]
I want to create a candlestick chart with data being updated every few seconds. The problem starts when I navigate the chart and then the update fires. What happens is, the chart gets completely rerendered and the current zoom level is reset to the default value. With updates being conducted often navigating gets pretty much impossible. Is it possible to update the chart with new data, but keep the current zoom level? Maybe I just have to somehow get the current zoom level whenever a new portion of data is presented and apply this zoom programmatically before the chart would be rerendered?

**Comment by Riddhish97** [comment]
Hey @SWi98 any update or solution about this issue?

**Comment by Jasper992** [comment]
Hey, i am encountering the same problem, are there any updates?

**Comment by davetapley** [comment]
For repro see [here](https://codesandbox.io/s/mzzq3yqjqj) (found via **Updating React Chart Data** in [docs](https://apexcharts.com/docs/react-charts/)):

1. Zoom chart in top left by drag selecting a time range
2. Click `Update!` button.

The chart will reset its zoom and pan.
