### ISSUE TITLE
Break/gap in line chart series when consecutive points contain the same value. 

### ISSUE THREAD

**Issue by jquiros2290** [apexcharts/react-apexcharts#288]
Using a line chart with stroke curve set to smooth, if the series data has at least two consecutive points with the same x-axis value, the series line will display a gap/break in data. When stroke curve set to straight you will see it makes one continuous line.  Both images below share the same data and configuration outside the difference in stroke curve. 

![smooth-line](https://user-images.githubusercontent.com/21298511/114562737-644e0800-9c34-11eb-9213-1c457a21b5c2.jpg)

![straight-line](https://user-images.githubusercontent.com/21298511/114562968-9b241e00-9c34-11eb-96df-aac7997f18fa.jpg)

**Comment by nokindj** [comment]
Any fix on this bug? 

Thank you.

**Comment by zilehuda** [comment]
Do we have any update or fix for this?
