### ISSUE TITLE
Changing xaxis options makes no effect

### ISSUE THREAD

**Issue by fatclient** [apexcharts/react-apexcharts#29]
Here I reproduced the issue: https://codesandbox.io/s/2511k0z0p
In my own chart I'm trying to implement[ those buttons](https://apexcharts.com/javascript-chart-demos/area-charts/datetime-x-axis/) to change time range. Options are stored in state and are passed to Chart. I change those options in state, but in makes no effect.

**Comment by junedchhipa** [comment]
Updated the above example (replaced vue.js example with react.js)

**Comment by junedchhipa** [comment]
I would like to see your `datetime` type example in codesandbox.
Meanwhile, in some days, I will re-create all examples on the website using react.js so you can easily use those as templates.

**Comment by fatclient** [comment]
I'm terribly sorry, It's all my fault and everything works as expected.

**Comment by junedchhipa** [comment]
No worries

**Comment by MaxLeiter** [comment]
I currently have this problem.

@junedchhipa shouldn't it be..


```javascript
this.setState({
  options: {
    ...this.state.options,
    xaxis: {
      ...this.state.options.xaxis,
        categories: ['X1', 'X2', 'X3']
      }
    }
  }
})

```

Notice the missing { after ...this.state.options.xaxis

**Comment by Lynnhan95** [comment]
Isn't it 
```
      this.setState({
        options: {
           ...this.state.options,
          yaxis: {
            ...this.state.options.yaxis,
              labels: {
                ...this.state.options.yaxis.labels,
                formatter: axisFormatter,
              }
            }
          }
        })
```
And same issue here, can't update yaxis option as I printed it out

**Comment by Lynnhan95** [comment]
It works now:)!!

**Comment by marslan2037** [comment]
i am still not able to update axis labels
