### ISSUE TITLE
Any `stroke.curve` value is marked by Typescript as "not assignable"

### ISSUE THREAD

**Issue by markodvornik** [apexcharts/react-apexcharts#296]
The `options.stroke.curve` parameter to Chart component has enum type. Typescript doesn't recognize any of the enum values when they are used in code.

When: `curve: "smooth"`
Typescript would throw an error: `Type 'string' is not assignable to type '"smooth"`

When: `curve: "smooth" as "smooth"`
Typescript would not complain.

**Environment**
react-apexcharts 1.3.9
Typescript 4.2.4.

**Expected**

We should be able to use enums from the typings, e.g. `curve: "smooth"`.

**A workaround example:**

```typescript
export default function LineChart({ series }) {

  const options = {
    chart: {
      type: "line" as "line",
      id: "line",
    },
    stroke: {
      curve: "smooth" as "smooth",
    }
  }

  return <Chart options={options} series={series} type="line" />
}
```

It's the same with `chart.type` as described in https://github.com/apexcharts/react-apexcharts/issues/289 .

**Comment by padovanitr** [comment]
You have two ways to solve this:

1 - Import apex typing
`import { ApexOptions } from 'apexcharts';`

and then use it

`const options: ApexOptions = {};`

2 - Tell typescript that your options object won't change.
So, add `as const` in the end of the declaration.

`const options = {} as const;`
