### ISSUE TITLE
Feature request: Full-controlled component

### ISSUE THREAD

**Issue by fatclient** [apexcharts/react-apexcharts#30]
Just a suggestion: It would be pretty useful, if these charts could be fully-controlled, i.e. could store their state externally, so we could programmatically react to users interactions with them (e.g. zooming in and out, etc.)  or change theirs state the way users do it.

**Comment by junedchhipa** [comment]
Good suggestion. However, there are ways where you can call methods/events on the chart instance programmatically. More info - https://github.com/apexcharts/react-apexcharts#how-to-call-methods-of-apexcharts-programatically

Although this may not feel like React way of doing things, it is a completely valid way of interacting with the chart instance.

```javascript
ApexCharts.exec('chart-id', 'updateSeries', [{
  data: [40, 55, 65, 11, 23, 44, 54, 33]
}])
```
