### ISSUE TITLE
crosshairs.width = "barWidth" is only supported in single series, not in a multi-series barChart. 

### ISSUE THREAD

**Issue by ttiras** [apexcharts/react-apexcharts#315]
I would appreciate if you could help me to get rid of the error in title. I get this even i don't set barWidth in the options.

**Comment by MMohesen** [comment]
the same

**Comment by yiqu** [comment]
Same for angular as well.

**Comment by lva98** [comment]
Same for Vue when `tooltip.intersect` and `tooltip.shared` are true

**Comment by RafaelSanaMontevechio** [comment]
The same for me.

**Comment by ttiras** [comment]
> Hello from `vue-apexcharts` 👋
> 
> Also ran into this problem. As I like the console to be clean of noise, I did this as a workaround:
> 
> ```
> crosshairs: {
>           show: false,
>           width: 1,
> },
> ```

I applied this code to xaxis and it worked. thanks alot.
