### ISSUE TITLE
Miscalculating Bar Position

### ISSUE THREAD

**Issue by yusufff** [apexcharts/react-apexcharts#32]
I couldn't find how this could happen so I decided to ask here:

![apexcharts-bug](https://user-images.githubusercontent.com/3111507/50883830-457bbe00-13fa-11e9-8680-551f08c5318f.gif)

![screen shot 2019-01-09 at 10 35 46](https://user-images.githubusercontent.com/3111507/50883862-5a585180-13fa-11e9-91e0-d549c4415deb.png)

As you can see, bar positions are shifted. My options:

```
<Chart options={options} series={series} type="bar" width="100%" height={400} { ...rest } />

options: {
	chart: {
		id: 'campaign-chart',
		type: 'bar',
		height: 400,
		stacked: false,
	},
	dataLabels: {
		enabled: false,
	},
	yaxis: [
		{
			seriesName: 'Number of Clicks',
			labels: {
				style: {
					color: '#6d7782',
				}
			},
			title: {
				text: 'Number of Clicks',
			},
			min: 0,
		},
	],
},
```

Do you have any idea how this could happen? There is no CSS affecting the graph.

**Comment by junedchhipa** [comment]
That’s strange. Can you please post the series prop too?

**Comment by yusufff** [comment]
@junedchhipa here is the series:
```
export const SubPubCTITDistMock = [
	{
		name: 'Number of Clicks',
		type: 'bar',
		data: [
			{x: 5, y: 20},
			{x: 10, y: 40},
			{x: 15, y: 150},
			{x: 20, y: 100},
			{x: 25, y: 80},
			{x: 30, y: 70},
			{x: 35, y: 60},
			{x: 40, y: 50},
			{x: 45, y: 40},
			{x: 50, y: 30},
			{x: 55, y: 20},
			{x: 60, y: 10},
			{x: 65, y: 8},
			{x: 70, y: 23},
			{x: 75, y: 36},
			{x: 80, y: 50},
			{x: 85, y: 70},
			{x: 90, y: 46},
		]
	}
];
```

**Comment by junedchhipa** [comment]
Can you please create a codesandbox demo of these?

Please use this react template of codesandbox - https://codesandbox.io/s/6yoqonyo7r

**Comment by yusufff** [comment]
@junedchhipa the position issue fixed for the bar chart after I updated the apexcharts version (line chart is same/broken). Here is the codesandbox: https://codesandbox.io/s/ovmo86n03q

As you can see in codesandbox, the last bar is halfway out of the chart and if you hover over the bar around 68 tick from x-axis, the 60 bar is after 68 tick. There is a problem with x-axis category distribution.

**Comment by junedchhipa** [comment]
Yeah, I noticed x-axis distribution for bar charts is broken. But, when I changed it to line chart, x-axis calculation was fine.

I will dig into the bar issue, and get back.

**Comment by junedchhipa** [comment]
Fixed it, the patch will be released soon this weekend.
