### ISSUE TITLE
Timeline Chart Needs Dynamic X-Axis Annotation for Large Data

### ISSUE THREAD

**Issue by asb9189** [apexcharts/react-apexcharts#321]
Hi Team!

I have been working with ApexCharts for the past couple of weeks and have been really impressed thus far. Recently, I have run into an issue that I cannot find a solution too, even when referring to the documentation. I am trying to graph a gantt chart (React-ApexChart Timeline Chart Distributed: https://apexcharts.com/react-chart-demos/timeline-charts/distributed/) with an abundance of data.

I'm currently rendering this chart in a scrollable container to make it easier to navigate vertically. However, the issue arises when the user is scrolling up and can no longer see the x-axis. This makes it hard to tell what time a particular action item started and finished without hovering over to see the tooltip. Here is an example:

<img width="1183" alt="snap" src="https://user-images.githubusercontent.com/54490650/125107764-2fc0df80-e0af-11eb-9844-47e2b6ee7610.png">

In the example above I have scrolled up far enough that I can no longer see the x-axis. What I would LOVE to see is something like this:

<img width="618" alt="example" src="https://user-images.githubusercontent.com/54490650/125107912-5848d980-e0af-11eb-81df-4e60dee718b6.png">

Is this possible using ApexCharts? Should I be rendering this data in a different fashion? Can the x-axis become 'sticky' and follow the user as they scroll up and down?

All help is much appreciated!

**Comment by ontheway16** [comment]
+1 on this.
