### ISSUE TITLE
wrong attributes on external div

### ISSUE THREAD

**Issue by rejetto** [apexcharts/react-apexcharts#324]
https://github.com/apexcharts/react-apexcharts/blob/19b8503e07bfe49301073af6b0ae6eaba329e572/src/react-apexcharts.jsx#L24

here you are passing all props to the div, while you probably should pass only those that are not extracted by getConfig().

The result is that the external div is rendered like this

        <div options="[object Object]" series="[object Object]" type="line" width="100%"

**Comment by iRyanBell** [comment]
Patched in PR https://github.com/apexcharts/react-apexcharts/pull/332
