### ISSUE TITLE
Cannot set property 'zoom' of undefined

### ISSUE THREAD

**Issue by morshedx** [apexcharts/react-apexcharts#331]

**Comment by kokolanskam** [comment]
i have the same problem on bar chart

**Comment by junedchhipa** [comment]
No reproduction information provided.

**Comment by hanuW3** [comment]
Comment toolbar option or enabled toolbar.

![image](https://github.com/user-attachments/assets/a2ebe6b4-836b-4cd2-a671-712287d92fe8)

**Comment by hanuW3** [comment]
> i have the same problem on bar chart


Comment toolbar option or enabled toolbar.

![image](https://github.com/user-attachments/assets/60167c10-30a8-4439-be8b-5ccd086ea383)
