### ISSUE TITLE
Documentation for apexcharts allows for a globa/default setting for colors for all charts. This does not seem possible in react-apexcharts.

### ISSUE THREAD

**Issue by rodpatulski** [apexcharts/react-apexcharts#339]
In documentation https://apexcharts.com/docs/colors/, we have the option to set global defaults for colors. This does not seem to be possible with react-apexcharts.

**Comment by joakimgrr** [comment]
Stumbled upon the same issue. Did you manage to find a solution for this @rodpatulski ?
