### ISSUE TITLE
bar charts in multi chart not displaying correctly

### ISSUE THREAD

**Issue by ThinkSalat** [apexcharts/react-apexcharts#34]
Here's what I'm getting
![screen shot 2019-01-16 at 12 35 22 pm](https://user-images.githubusercontent.com/31082405/51277252-e387ff00-198b-11e9-91e5-9a469fec11c9.png)

The bar should only cover the one data point, but it fills the entire graph.
It should be simple to get these bars to show up correctly but they're not showing up right. When you hover over the bar, it starts glitching out. 

when you click to remove the first dataset from the graph, it also removes the second dataset from the graph. Please give me some guidance here, I've been banging my head against the wall trying to figure this one out. The docs have not been much help either.

here's the data: 

My first series: data: [{x: "15-Jan-19", y: 3}], type: line
second series: data: [{x: "15-Jan-19", y: 2}], type: bar

yaxis and annotations are generated before this based on the data.

options = {
    chart: {
      fontFamily: 'Quicksand, Times New Roman, Times, serif, sans-serif',
      toolbar: { show: false },
      zoom: { enabled: false },
    },
    markers : { size:  [5,5] },
    stroke: { size: [5,5],
    dataLabels: { enabled: false },
    selection: { enabled: false },
    tooltip: {
      enabled: true,
      shared: true,
      followCursor: false,
      fixed: {
        enabled: true, 
        position: 'top'
      }
    },
    plotOptions: {
      bar: {
        horizontal: false,
        endingShape: 'flat',
        columnWidth: '70%',
        barHeight: '70%',
        distributed: true
      }
    },
    xaxis: {
      type: 'datetime',
      crosshairs: { show: true },
      tooltip: { enabled: false },
      max: Date.now(),
      min,
    },
    yaxis,
    annotations,
  }

**Comment by junedchhipa** [comment]
@ThinkSalat Sorry for the trouble you faced in this regard. Looking at the screenshot, it looks like a bug in single dataPoints series. I will check soon and get back.

**Comment by junedchhipa** [comment]
@ThinkSalat 
Thanks for the additional info.
Also, your configuration was missing some parenthesis (`stroke` is missing its closing bracket). 
Anyway, I have fixed the bug in the last commit - https://github.com/apexcharts/apexcharts.js/commit/69cabe0c269d903592036ac138344dacdea4e4a4 and will be releasing a patch soon.
I will try to create a codepen when I do a release to demonstrate the use-case.
