### ISSUE TITLE
Dashed Line Chart render bug when working with "big" array

### ISSUE THREAD

**Issue by rafacepsa** [apexcharts/react-apexcharts#346]
Hello, 

I encountered a bug (latest version of react-apexcharts) in the dashed line chart. 

You can reproduce this bug if you insert in the series prop an array of 4 elements or more.  

Image of chart with an array of 3 elements
![image](https://user-images.githubusercontent.com/84703609/135257179-6308d373-a6a8-4bed-b371-8794520f1085.png)

Image of chart with an array of 4 or more elements
![image](https://user-images.githubusercontent.com/84703609/135257305-189344ad-bb51-406d-8ff0-11484f6d53a2.png)

I don't know if its a known issue but I could't find any information about it.

**Comment by Saddi993** [comment]
I have used these options, data labels and animations.


```
options: {
 dataLabels: {
   enabled: false
 },
 chart: {
  animations: {
   enabled:false
  }
 }
}
```
