### ISSUE TITLE
specifying stackType: "100%" gives the error Type 'string' is not assignable to type '"normal" | "100%" | undefined'

### ISSUE THREAD

**Issue by rodpatulski** [apexcharts/react-apexcharts#347]
I'm trying to create a simple stacked, 100%-type bar chart as per the docs:

https://apexcharts.com/vue-chart-demos/bar-charts/stacked-100/

However, whenever I try to specify a stacked bar type as a stackType of 100%:

`options: {
            colors: ['#9B51E0'],
            background: '#FFAFFC',
            title: {
                text: 'Weekly Progress',
                style: {
                    fontSize: '16px',
                    fontWeight: 'normal',
                    fontFamily: 'IBM Plex Sans, sans-serif',
                    color: '#53599A'
                }
            },
            chart: {
                id: "basic-bar",
                stacked: true,
                stackType: "100%"
            },
            xaxis: {
                categories: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
                position: 'bottom',
                labels: {
                    show: true,
                    style: {
                        colors: ['#53599A', '#53599A', '#53599A', '#53599A', '#53599A', '#53599A', '#53599A'],
                        fontSize: '12px',
                        fontFamily: 'IBM Plex Sans, sans-serif',
                        cssClass: 'apexcharts-xaxis-label'
                    }
                }
            },`

I get the error: No overload matches this call.... Type 'string' is not assignable to type '"normal" | "100%" | undefined'.

Even though apexchart.d.ts defines it as:
`stackType?: 'normal' | '100%'`

**Comment by vexxvakan** [comment]
dropping to see if anyone knows how to work around this. Currently facing the same issue and can't seem to find a good way to make it work.

**Comment by rodpatulski** [comment]
Current and sad workaround is to modify your apexcharts.d.ts file so that stack type is a string. That worked for. me just to see what my chart would look like, but obviously this is not a long-term solution.

**Comment by rodpatulski** [comment]
It seems like this caused by the way TypeScript was designed. When passing in 
`stackType: '100%'`
TypeScript treats stackType as a string type but ApexOptions expects to be of type ''normal' | '100%', in otherwords a string literal type...not string. More info in the [docs](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#literal-inference).

Closing issue.
