### ISSUE TITLE
Changing chart options do not update the rendered chart

### ISSUE THREAD

**Issue by Pavinati** [apexcharts/react-apexcharts#349]
Changing options won't trigger a re-render with updated options

minimal codepen example: https://codepen.io/Pavinati/pen/BadKYPr

**Comment by Blackglade** [comment]
Ran into the same issue. This is actually a big pain point of react apexcharts. Current workaround (super hacky) was just to do add `chart-${Math.random()}` to the id key in the chart options object "forcing" a re-render of the options everytime.
