### ISSUE TITLE
fill gradient not working?

### ISSUE THREAD

**Issue by npomfret** [apexcharts/react-apexcharts#35]
I'm trying to reproduce this https://apexcharts.com/samples/vanilla-js/line/zoomable-timeseries.html which has a fill gradient.  I can't get it to work though.  The gradient appears to be on the line colour, not the area under the line.

using:

    "apexcharts": "^3.1.0",
    "react-apexcharts": "^1.2.1",

**Comment by junedchhipa** [comment]
Can you please post the codepen or paste the whole config which you tried?

**Comment by junedchhipa** [comment]
The configuration in that sample is incorrect, which I will change soon.

You have to enable gradient like this
```javascript
fill: {
        type: 'gradient',
        gradient: {
          shadeIntensity: 1,
          opacityFrom: 0.7,
          opacityTo: 0.9,
          stops: [0, 100]
       }
},
```

**Comment by npomfret** [comment]
@junedchhipa thanks, i tried but I just can't seem to get the gradient fill to work.  Here's the code:

https://gist.github.com/npomfret/30519f77d7af72d0e43817de5f6ac5b4

**Comment by npomfret** [comment]
@junedchhipa think you missed something there

**Comment by npomfret** [comment]
ah, adding `type='area'` seemed to do the trick!
