### ISSUE TITLE
Leader Labels on Donut/Pie Chart and Persist Value onClick

### ISSUE THREAD

**Issue by omairnabiel** [apexcharts/react-apexcharts#36]
An option to provide leader labels with values to pie/donut chart.
Other than that the chart shows value of a portion only when hovered upon. It must also persist the value when a portion is selected.

**Comment by junedchhipa** [comment]
Can you provide elaborate which leader labels you're talking about? The labels which appear inside donut area?

**Comment by omairnabiel** [comment]
No the ones that are outside. Check out the attached image 
![donut](https://user-images.githubusercontent.com/13148988/52036810-79588800-254f-11e9-93a1-7a87fc25378e.png)

**Comment by omairnabiel** [comment]
The other issue is when a section is clicked. It does expand and gets accentuated but the value of that selected portion doesn't appear in the center only when hovered on

**Comment by junedchhipa** [comment]
@omairnabiel Sorry for the delay. The issue of not persisting label when a slice is selected has already been fixed and should be visible in `apexcharts@3.6.10`.

**Comment by adolfodelarosa93** [comment]
> No the ones that are outside. Check out the attached image ![donut](https://user-images.githubusercontent.com/13148988/52036810-79588800-254f-11e9-93a1-7a87fc25378e.png)

@omairnabiel  How to put the labels with lines?

**Comment by nidhishkrishnan** [comment]
@adolfodelarosa93 did you got any breakthrough for this?
