### ISSUE TITLE
Adding width to chart does not appear to change the width of the chart

### ISSUE THREAD

**Issue by careignition-cps** [apexcharts/react-apexcharts#366]
Adding width: '50%' appears to make no difference to the chart. The xaxis is too long, and I want the graph in a square shape, which I don't see how to do. 

```
chart: {
      id: 'qualityCost',
      type: 'scatter',
      width: '1%'
    }
```
results in the chart looking exactly like
```
chart: {
      id: 'qualityCost',
      type: 'scatter',
      width: '100%'
    }
```

**Comment by AVATAR197** [comment]
If you are using react you are supposed to set width by passing width as a prop to the component.

![image](https://user-images.githubusercontent.com/39923116/146999456-fea709a1-ee23-47db-97d8-e72fb6b3d039.png)
