### ISSUE TITLE
Version Update. MultiAxis Chart not rendering Properly

### ISSUE THREAD

**Issue by omairnabiel** [apexcharts/react-apexcharts#37]
I updated my apex charts library recently and here's what I get when using multi-axis chart. For some reason it doesn't render properly sometimes. Here are the two images one with the old version apexcharts(2.2.2) and the other with newer version I updated to apexcharts(3.2.1)

Old Version
![oldversionapexpng](https://user-images.githubusercontent.com/13148988/52348606-8e00b880-2a46-11e9-8d43-bc2e39194526.PNG)

New Version
![newversionapex](https://user-images.githubusercontent.com/13148988/52348619-9822b700-2a46-11e9-8ddd-1e2b751aee5b.PNG)

The graph has exactly the same data in both images. The only thing I changed was the apexcharts version.
Thanks

**Comment by junedchhipa** [comment]
Would you be able to create a codepen demo for the new chart? So that I can easily reproduce it.

**Comment by junedchhipa** [comment]
Did you found a workaround for it? Does this issue still exist?

**Comment by omairnabiel** [comment]
Sorry I''ve been busy with the work and couldn't reply. I've downgraded my library to fix the issue. However I can you provide you with the dataset on which the problem was occuring?

**Comment by junedchhipa** [comment]
Sure, please provide the dataset and the configuration of the chart
