### ISSUE TITLE
Error on chart scatter dataLabel

### ISSUE THREAD

**Issue by vianafgbluiz** [apexcharts/react-apexcharts#371]
Hello, when using the scatter chart, with:
dataLabels: {
             enabled: true
}
At various times all dataLabels are not displayed, sometimes 20% without displaying, but I have not found a pattern.

![WhatsApp Image 2022-01-07 at 16 02 11](https://user-images.githubusercontent.com/45015402/148595920-f22e8897-37f4-4c43-a6a3-033c126e4fd2.jpeg)
![WhatsApp Image 2022-01-07 at 16 04 47](https://user-images.githubusercontent.com/45015402/148595924-79d0c845-e926-486b-9177-afd9176a0c28.jpeg)
.

**Comment by AlaaCherif** [comment]
I also have this issue it's when the points are too close there's a way to disable it that in this [issue](https://github.com/apexcharts/apexcharts.js/issues/618) but it's only for bar charts and i can't seem to find the equivalent in scatter.
