### ISSUE TITLE
Safari: legend position will offset when zoom in

### ISSUE THREAD

**Issue by busyxiang** [apexcharts/react-apexcharts#381]
<img width="746" alt="Screenshot 2022-02-09 at 2 44 12 PM" src="https://user-images.githubusercontent.com/19426419/153136532-b12ddf3d-e864-44cf-8407-11a1105e9e3e.png">

**Comment by busyxiang** [comment]
Report the issue in the JS repository instead https://github.com/apexcharts/apexcharts.js/issues/2963, will close this issue

**Comment by junedchhipa** [comment]
The issue is fixed in the latest version of apexcharts@4.5.0
