### ISSUE TITLE
apexcharts hide bottom Series 

### ISSUE THREAD

**Issue by shakil-brl** [apexcharts/react-apexcharts#395]
![image](https://user-images.githubusercontent.com/76032597/162713198-0afe979f-1ec3-457d-89a8-94fa7ad97342.png)
**How can i hide this label from chart**

**Comment by shakil-brl** [comment]
@brianlagunas @kkirsche @kdinev @bernardofd any buddy can help with this issue please

**Comment by kdinev** [comment]
@shakil-brl I'm able to remove the `xaxis` labels by settings `categories: [""]` in the `chartOptions`.

```typescript
xaxis: {
  categories: [""]
}
```
