### ISSUE TITLE
Line Chart - Multiline Text in Axes Labels not Working

### ISSUE THREAD

**Issue by theusner-thing** [apexcharts/react-apexcharts#403]
Hi,

I was trying to apply multiline text on line charts https://apexcharts.com/docs/multiline-text-and-line-breaks-in-axes-labels/

But it seems that this is not working as expected:

![image](https://user-images.githubusercontent.com/54796636/170240526-63048849-37d7-4d22-9674-52b3bf32b40e.png)

You can find a sample on:
https://stackblitz.com/edit/x-apex-charts-zxjimh?file=index.js

Chart options are as follows:
`var options = {
  chart: {
    height: 350,
    type: "line"
  },
  stroke: {
    curve: 'smooth',
    width: 1.8
  },
  xaxis: {
    type: "category",
    categories: [
      "A",
      ["First", "Second"],
      "C"
    ]
  },
  colors: ["#00ff88", "#ff00ff"],
  yaxis: [
    {
        "min": 0,
        "max": 100,
        "opposite": false,
    }
  ],
  series: [
    {
        "name": "Series 1",
        "data": [100, 20, 30]
    },
    {
      "name": "Series 2",
      "data": [5, 50, 80]
    }
  ]
};`

**Comment by junedchhipa** [comment]
This bug is fixed in the latest version of [apexcharts 3.35.3](https://www.npmjs.com/package/apexcharts/v/3.35.3)
