### ISSUE TITLE
reading type error apexcharts

### ISSUE THREAD

**Issue by RamboGj** [apexcharts/react-apexcharts#406]
I'm getting an error when rendering a donut chart on apexcharts. In the same page, I have many charts, but this one is returning the following error: "TypeError: Cannot read properties of undefined (reading 'type')"
![Screenshot_1](https://user-images.githubusercontent.com/64593022/171049440-c76258fa-9ddc-4db3-896d-83e3730a7ad8.png)

**Comment by MD-Mehedi-Hasan18111** [comment]
**### Hey! Did you solve it? I also face this issue in my project. Please if you did already solve then let me know the solution.**

![image](https://user-images.githubusercontent.com/86622586/191092531-834e4d63-6686-4f9b-ab5d-3a90b3076885.png)

**Comment by HarrisFauntleroy** [comment]
+1
