### ISSUE TITLE
Chart series does not show the latest update with the same labels

### ISSUE THREAD

**Issue by Charles-XD** [apexcharts/react-apexcharts#418]
Steps to reproduce:
1. [https://apexcharts.com/react-chart-demos/pie-charts/update-donut/](https://apexcharts.com/react-chart-demos/pie-charts/update-donut/)
2. Click randomize button to get new data
3. Change the page zoom

expected behavior: 
chart should display the latest values 

current behavior: 
chart series change to the previous data

this issue also happens if the size of the charts parent element changes.

**Comment by moigarcia** [comment]
Hi @Charles-XD, you managed to solve the problem, the same thing is happening to me.

**Comment by moigarcia** [comment]
I found the solution, in my case, the problem was that the id was not updated in the options when de series was updated and always passed the same and that produced the error.

**Comment by Charles-XD** [comment]
Hi @moigarcia 
I changed redrawOnWindowResize: false, redrawOnParentResize: false properties for my charts but your solution is better 
did you set this id [https://apexcharts.com/docs/options/chart/id/](https://apexcharts.com/docs/options/chart/id/) ?

**Comment by moigarcia** [comment]
Yes, i update this id every time the component is updated.
