### ISSUE TITLE
Cannot call react testing library cleanup() function when rendering apex-charts

### ISSUE THREAD

**Issue by rodpatulski** [apexcharts/react-apexcharts#427]
When I test drawing any apex chart, when calling cleanup, I get the following error:

 Error: Uncaught [TypeError: this.node.getScreenCTM is not a function]

I'm using jest and by calling cleanup like this (using jest)
`afterEach(cleanup)`
I get the above error.

**Comment by rodpatulski** [comment]
Update: The same thing happens even after calling cleanup(); at the end of a test.

**Comment by rodpatulski** [comment]
Another update:
I tried clonging react-apexcharts and running the react-apexcharts.test.js and it has the same issue. 

Whenever 
`ReactDOM.unmountComponentAtNode(div);`
is called. You get an error ' TypeError: Cannot read property 'node' of undefined'

Note:this calls 'componentWillUnmount' and eventually this.chart.destroy() in apexcharts.common.js but that's as far as I've gotten. Commenting out unmountComponentAtNode, fixes the problem.

**Comment by rodpatulski** [comment]
Note: This is a show stopper for unit testing react-apexcharts and I'm assuming apexcharts, since there is no way to clean up between unit tests.

**Comment by nt294** [comment]
Any luck resolving this? I'm encountering the same issue when trying to test using React Testing Library

**Comment by rodpatulski** [comment]
No luck. I've moved on to cypress.
