### ISSUE TITLE
Getting an error for while dragging and dropping a Chart regarding the height being NaN and whole page crashes

### ISSUE THREAD

**Issue by noobDev31** [apexcharts/react-apexcharts#432]
I am trying to use the **ReactApexChart** in my low code app and my code is the following - 

`/* eslint-disable no-console */
import ReactApexChart from 'react-apexcharts';
import {ApexOptions} from 'apexcharts';
import {TCommonBaseProps} from '../../common';

export type TChartProps = TCommonBaseProps
& {
    type?: 'line' | 'area' | 'bar' | 'histogram' | 'pie' | 'donut' | 'radialBar' | 'scatter'
    | 'bubble'
    | 'heatmap'
    | 'treemap'
    | 'boxPlot'
    | 'candlestick'
    | 'radar'
    | 'polarArea'
    | 'rangeBar';
    series?: Array<any>;
    width?: string | number;
    height?: string | number;
    options?: ApexOptions;
    [key: string]: any;
};

const ChartLowCode = (props: TChartProps): JSX.Element => {
    const {series = [], options = {}, type = 'bar'} = props;
    return (
        <ReactApexChart
            {...props}
            series={series}
            options={options}
            type={type}
        />
    );
};

export {ChartLowCode as Chart};`

But I get the following error in the console something like this - 

![image](https://user-images.githubusercontent.com/109504204/191014292-3309504b-8d3e-40d8-a892-1aa0a72d785d.png)

**Comment by noobDev31** [comment]
i have also tried giving a **height = '100%'** as a **default** to the the **ReactApexChart**

**Comment by noobDev31** [comment]
`import ReactApexChart from 'react-apexcharts';
import {ApexOptions} from 'apexcharts';
import {TCommonBaseProps} from '../../common';

export type TChartProps = TCommonBaseProps
& {
    type?: 'line' | 'area' | 'bar' | 'histogram' | 'pie' | 'donut' | 'radialBar' | 'scatter' | 'bubble'
        | 'heatmap' | 'treemap' | 'boxPlot' | 'candlestick' | 'radar' | 'polarArea' | 'rangeBar';
    series?: ApexAxisChartSeries | ApexNonAxisChartSeries;
    options?: ApexOptions;
};

const ChartLowCode = (props: TChartProps): JSX.Element => {
    const {series = [], options = {}, type = 'bar'} = props;
    return (
        <ReactApexChart
            {...props}
            series={series}
            options={options}
            type={type}
            height="100%"
            width="100%"
        />
    );
};

export {ChartLowCode as Chart};
`

Update - The above code works I don't know why

**Comment by DatTN95** [comment]
hi [noobDev31](https://github.com/noobDev31), Have you solved the problem?
