### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'type') for Apex Chart in react js

### ISSUE THREAD

**Issue by MD-Mehedi-Hasan18111** [apexcharts/react-apexcharts#433]
### I get this error when I am using the apex chart. I also pass the props type for chart. after reloading the page I get this error I don't understand why I get this error. Please help!

![image](https://user-images.githubusercontent.com/86622586/191105401-7fb694c1-bfff-4f5d-adaa-2ba5f2b48cf6.png)
![image](https://user-images.githubusercontent.com/86622586/191105478-df1002ae-4f38-4398-89a1-b59986ac3758.png)

**Comment by HarrisFauntleroy** [comment]
+1

**Comment by ekiankim92** [comment]
@MD-Mehedi-Hasan18111 were you able to fix this issue?
