### ISSUE TITLE
Apexcharts causes gatsby builds to fail

### ISSUE THREAD

**Issue by cameronblandford** [apexcharts/react-apexcharts#44]
Hi guys! First of all, thank you for the amazing library. I've only been using it for a few hours but I already love it.

So react-apexcharts works amazingly on a gatsby dev server, but when I try to build to a static page for deployment (`npm run build / gatsby build`), I get the below:

Any idea what might be causing this? Is it an issue with SSR possibly? Removing react-apexcharts and apexcharts fixes the issue.
```
success Building production JavaScript and CSS bundles — 17.788 s

error Building static HTML failed

See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html

  19048 |     });
  19049 |   } else if ((typeof exports === "undefined" ? "undefined" : _typeof(exports)) === 'object') {
> 19050 |     module.exports = root.document ? factory(root, root.document) : function (w) {
        | ^
  19051 |       return factory(w, w.document);
  19052 |     };
  19053 |   } else {


  WebpackError: TypeError: Cannot read property 'document' of u  ndefined
  
  - apexcharts.esm.js:19050 
    [lib]/[apexcharts]/dist/apexcharts.esm.js:19050:1
  
  - apexcharts.esm.js:19056 Module.<anonymous>
    [lib]/[apexcharts]/dist/apexcharts.esm.js:19056:2
  
  
  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1
  
  - react-apexcharts.min.js:1 Object../node_modules/react-apexc    harts/dist/react-apexcharts.min.js
    [lib]/[react-apexcharts]/dist/react-apexcharts.min.js:1:722  
  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1
  
  
  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1
  
  
  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1
  
  - sync-requires.js:9 Object../.cache/sync-requires.js
    lib/.cache/sync-requires.js:9:56
  
  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1
  
  - static-entry.js:9 Module../.cache/static-entry.js
    lib/.cache/static-entry.js:9:22
  
  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1
  
  - bootstrap:83 
    lib/webpack/bootstrap:83:1
  
  

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-homepage@0.1.2 build: `gatsby build`
npm ERR! Exit status 1
```

**Comment by junedchhipa** [comment]
The error is due to SVG.js expecting the `document` to be present. The existing version of SVG.js in ApexCharts has support only for the browser environment.

Soon, SVG.js in ApexCharts will be upgraded to v3.0 which is a major rewrite and hopefully will have better SSR support.

**Comment by cameronblandford** [comment]
Awesome! Thank you for the quick reply! Is there an order-of-magnitude estimate for how long `soon` will most likely be?

**Comment by junedchhipa** [comment]
The migration from svg.js v2 to v3 is going on actively - https://github.com/apexcharts/apexcharts.js/tree/svgjs3.0

Don't have an estimated timeline as there are many breaking changes and a lot of stuff to be taken care of before another major release. Also, the plugins that depend on svgjs3.0 are still not ready to be used with the latest core library. Hence, a timeline of 2-3 months (quite long) is estimated.

We announce updates on twitter https://twitter.com/apexcharts so you may follow us there for any major releases.

**Comment by christianbueschi** [comment]
Any news on that?

**Comment by gxwheel152** [comment]
Also interested in the upgrade to SVG.js v3. Any word or updates on timelines ? 
Thanks in advance 
![image](https://user-images.githubusercontent.com/42223563/63402668-757c3e00-c399-11e9-8c27-25d3cbfeda6f.png)

**Comment by gxwheel152** [comment]
Has anyone tried to do this directly with JavaScript instead of using the React wrapper? Just curious.

**Comment by vik-borisov** [comment]
Has any news?

**Comment by areljannC** [comment]
@vik-borisov, @gxwheel152, @cameronblandford 

Hi guys!

I recently came across this exact same issue but with different errors. I'll cut straight to what worked for me. 

https://www.gatsbyjs.org/docs/using-client-side-only-packages/#workaround-3-load-client-side-dependent-components-with-react-loadable

According to GatsbyJS' docs, they recommend a workaround of using a library called [Loadable Components](https://github.com/smooth-code/loadable-components).

Here's how structure my components imports a **Chart** from **react-apexcharts**:
```
import React from "react"
import Loadable from '@loadable/component'

const ComponentWithChart = ({ options, series }) => (
  <>
    <LoadableChart  
        options={options} 
        series={series} 
        type="bar"
        height="350"
    />
  </>
)

export default ComponentWithChart

// import react-apexcharts here
const LoadableChart = Loadable(() => import(../pathToNodeModules/node_modules/react-apexcharts/src/react-apexcharts))
```

The takeaway here is, instead using **Chart** directly, use **Loadable Components** as a wrapper to import **react-apexcharts** and use the wrapped chart in your component.

I think this is a _hacky solution_ but I have searched everywhere for a solution and this is the only one that has worked for me so far.

I hope it works for you, otherwise, please let me know other different solutions.

**Comment by ar000n** [comment]
You can skip the particular component from building html by
adding below configuration. Its basically returns a null for mentioned component on build-html stage.
`exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
  if (stage === "build-html") {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /bad-module/,
            use: loaders.null(),
          },
        ],
      },
    })
  }
};`
reference [https://www.gatsbyjs.org/docs/debugging-html-builds/](url)

**Comment by pacocom** [comment]
For developer mode I need to use loadable too, why?? If I don't use loadable appears this error https://github.com/apexcharts/apexcharts.js/issues/1749 (I open the PR).

Thank.

**Comment by Kam125** [comment]
any update on this issue,

**Comment by Kam125** [comment]
Was having the same issue and applied the skip option, on local dev ssr was enabled so it was giving error, but when I disabled it and build on gatsby cloud, it worked.

**Comment by BFMarks** [comment]
sad panda
