### ISSUE TITLE
Annotations are not getting full width and the XAxis values get cut when the columnWidth is less

### ISSUE THREAD

**Issue by noobDev31** [apexcharts/react-apexcharts#442]
I have two issues on my codesandbox - 

https://codesandbox.io/s/react-apexcharts-bar-chart-forked-76pvlt?file=/src/index.js

a) The XAxis as you can see I am not getting the last value(**May 2022**) and for various screen sizes it happens - 
The value  is getting cut somehow and I am getting the value when I change the column width to **22%** it works only then(Attached screenshot)

I tried with **chart: { width: "100% }** as well still doesn't work.

b)The annotations(parallel to the XAxis) line is not having a full width for the average as you can see in the screenshots. 
<img width="959" alt="Screenshot_324" src="https://user-images.githubusercontent.com/109504204/195426146-fff926d2-c508-431a-baf4-75a4de6fecde.png">

<img width="914" alt="Screenshot_325" src="https://user-images.githubusercontent.com/109504204/195426170-1c0f2bb3-d405-4314-ba99-db0ed54db0fb.png">

<img width="637" alt="Screenshot_322" src="https://user-images.githubusercontent.com/109504204/195425592-4b6c3656-4230-479d-ace6-56a511d0679c.png">

 @junedchhipa / @brianlagunas  can you please have a look at it

**Comment by AndreGuimRua** [comment]
I'm currently experiencing the same issue. The only workaround that i've found is changing the annotations offsetX and width
   ```
 annotations: {
      yaxis: [
        {
          y: 33.9,
          offsetX: -20,
          width: '115%',
          borderColor: '#000',
        },
        {
          y: 33.1,
          offsetX: -20,
          width: '115%',
          borderColor: '#000',
        }]
}
```

There is any alternative to this?
