### ISSUE TITLE
Stacked Bar Charts not displaying totals

### ISSUE THREAD

**Issue by Shadowfita** [apexcharts/react-apexcharts#447]
Hi,

I'm following the demo shown here: https://apexcharts.com/react-chart-demos/bar-charts/stacked/ - and with an identical config, I am not getting any totals displayed.

Is there an issue with totals in the react version?

Thanks.

**Comment by iamRamkumar** [comment]
I am also facing the same issue. any update on that?

**Comment by Shadowfita** [comment]
For whatever reason I get the totals as expected when I compile my site on another machine. There must be some difference or library version somewhere causing the discrepancy.
