### ISSUE TITLE
Support for rangeArea charts

### ISSUE THREAD

**Issue by JackSacali** [apexcharts/react-apexcharts#449]
Hi,

Is there any plan to add support for the new chart type: rangeArea to react-apexcharts?

Thanks!

**Comment by MuhammadAyaz33** [comment]
Getting following console error while following documentation for rangeArea chart.
<img width="799" alt="image" src="https://user-images.githubusercontent.com/33997607/203032785-8ecf41b8-3f9d-490f-b0c6-19d63971b826.png">

**Comment by shechter** [comment]
👍

**Comment by JackSacali** [comment]
I created this workaround to make the build pass for now:
Create a new type and use it override the imported `ReactApexChart` component 
```
import React from 'react';
import { Props } from 'react-apexcharts';

export type ReactApexchartsWithExtendedProps = typeof React.Component<Omit<Props, 'type'> & {
  type?: 'line'
  | 'area'
  | 'bar'
  | 'histogram'
  | 'pie'
  | 'donut'
  | 'radialBar'
  | 'scatter'
  | 'bubble'
  | 'heatmap'
  | 'treemap'
  | 'boxPlot'
  | 'candlestick'
  | 'radar'
  | 'polarArea'
  | 'rangeBar'
  | 'rangeArea';
}>;
```

**Comment by BrianBelhumeur** [comment]
Submitted PR #507 as a fix.
