### ISSUE TITLE
Launch zoom event using React

### ISSUE THREAD

**Issue by lucaswerner90** [apexcharts/react-apexcharts#45]
Hi guys! First of all thanks for such great library! I appreciate all the work that you put in here! :D 

I have a question, I'm using the library with React, so far, everything is ok but I would like to programatically launch a zoom event and I don't know how to do it.

`<Chart
            id="chartID"
            options={options}
            series={series}
            type="area"
            width="100%"
            height="350px"
          />`

This is my chart within the render() method. I've read that I can use exec for that purpose, is it correct? Have you ever tried it? Thanks!

**Comment by lucaswerner90** [comment]
Thanks for your answer! Finally I came up with a similar solution as the one you mentioned. I appreciate the support

**Comment by jatindumka** [comment]
@lucaswerner90  did you try zooming effect in heatmap???? for me its not working.!!
any clue???

**Comment by khalvinNucom** [comment]
Using zoomX with exec() is working fine with me. I had a problem before because of extra spaces in the parameters like here   `ApexCharts.exec('zoomChart','zoomX ',1607212800000, 1606953600000);`

check out this working code. I hope it helps specially for react or vue devs

https://codepen.io/khalvin/pen/PoGqXWZ

**Comment by Huzaif-Ahmed** [comment]
i am also using the apex charts in react and facing same issue

` const chartRef = useRef(null); // Create a ref to store the chart instance

  const zoomChart = (start, end) => {
    if (chartRef.current) { // Check if the chart reference is available
      chartRef.current.chart.zoomX(start, end); // Use the ref to access the chart instance and zoom
    } else {
      console.error('Chart reference not available yet. Zoom failed.'); // Handle potential errors
    };
  
  };
  return (
    <div>
      <div className=' mb-4 '>
        <button className='ms-auto p-3 text-blue-600 rounded-md border-black bg ' onClick={() => zoomChart(new Date('2017-02-01').getTime(), new Date('2017-03-31').getTime())}>1 Month</button>
        <button className='p-3 text-blue-600 rounded-md border-black bg ' onClick={() => zoomChart(new Date('2017-01-01').getTime(), new Date('2017-06-30').getTime())}>6 Months</button>
        <button className='p-3 text-blue-600 rounded-md border-black bg ' onClick={() => zoomChart(new Date('2017-01-01').getTime(), new Date('2017-12-31').getTime())}>1 Year</button>
        <button className='p-3 text-blue-600 rounded-md border-black bg ' onClick={() => zoomChart(new Date('2017-01-01').getTime(), new Date('2017-04-30').getTime())}>YTD</button>
        <button className='p-3 text-blue-600 rounded-md border-black bg ' onClick={() => zoomChart(new Date('2017-01-01').getTime(), new Date('2017-05-15').getTime())}>All</button>
      </div>
      <ApexChart  type="area" options={options} series={series} height={400} width={900} ref={chartRef}/>
    </div>
  )
} `

i dont know why but my onclick functions are not working
