### ISSUE TITLE
Apex charts does not render in Production in NextJS

### ISSUE THREAD

**Issue by irffanasiff** [apexcharts/react-apexcharts#456]
I am using react-apexcharts with nextjs 13. Rendering it on client side works fine but in production the charts do not render.  

Here is the demo of what happens when i run ```pnpm run start```
https://www.loom.com/embed/b842f9436adc4dd881e59fdb08749bd7

This is only when i run build. there is no issue in development. Here is the code i reproduced a minimum version of it 
[Codesandbox](https://codesandbox.io/p/github/irffanasiff/apexcharts-issue-reproduction/draft/wizardly-murdock?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522clata6jvg000h7pfja1rcagvi%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clata6tyr00653b77x3hgor46%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

![Screenshot 2022-11-23 at 12 37 27 PM](https://user-images.githubusercontent.com/74172466/203489313-c2c3418e-6c8a-4fb0-9376-20220acd00d7.png)

**Comment by jxclsv** [comment]
Same problem in my local machine the chart works fine but in production mode it stutters

i've tried to downgrade to nextjs v12 it works on production

**Comment by irffanasiff** [comment]
so the problem is with nextjs 13. i cant afford to do that

**Comment by jxclsv** [comment]
that's the fastest route i guess 😢

**Comment by baljeetjangra** [comment]
I upgraded to latest version 13.4 and its resolved

**Comment by rojofan** [comment]
I'm using Next 13.4.4 and I'm encounter below error. On top of that resizing the chart for responsive setup won't work neither. Actually, resizing won't work at all.
Did you guys experience something similar? 
  
<img width="548" alt="image" src="https://github.com/apexcharts/react-apexcharts/assets/15306373/1aa8896b-cd01-4fb5-990d-31d61e48fd54">
