### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')  at t.value (apexcharts.common.js:6:1)

### ISSUE THREAD

**Issue by narutodev123** [apexcharts/react-apexcharts#467]
Hi Team,
I am facing this issue when i am lazy loading the apex chart library like this in the dev local environment.

--Getting error with the below case.
const ReactApexChart = React.lazy(() => (import(/* webpackChunkName: "apex-chars" */ "react-apexcharts")));

--Working fine
 import ReactApexChart from "react-apexcharts";
 
 Note: The component in which this chart is used is also Lazy Route Component

**Comment by andrewgbliss** [comment]
I am getting this error also in dev local environment. It was working for me, but now its this error

**Comment by luanelioliveira** [comment]
Yes, I'm getting too..

**Comment by luanelioliveira** [comment]
This problem is related to NextJs in version 13. I downgraded to version 12 and it worked for me.

**Comment by cvanem** [comment]
> This problem is related to NextJs in version 13. I downgraded to version 12 and it worked for me.

Can confirm.  I get this error with next 13.07 and 13.1.  I was not getting this previously when using next 12.x.

**Comment by narutodev123** [comment]
I am getting this error in React 18.1.0

**Comment by cvanem** [comment]
In my scenario, I traced the code to a width.toString operation with an undefined width causing the exception.  Explicitly setting the width on my chart to 100% has resolved the issue for me.

I Changed this:
`<Chart height={360} options={chartOptions} series={chartSeries} type='area' />`

To This:
`<Chart height={360} width='100%' options={chartOptions} series={chartSeries} type='area' />`

**Comment by lokimckay** [comment]
@cvanem's solution also solved my issue using Next13 👍 thanks!

For any maintainers that reads this: these are the 2 places I could see `.width.toString()` mentioned in the [apexcharts.js repo](https://github.com/apexcharts/apexcharts.js)

[src/modules/Core.js#L362-L363](https://github.com/apexcharts/apexcharts.js/blob/e5fee6a572e714daf85ad91fbe4ce81affb82fe2/src/modules/Core.js#L362-L363)

[src/modules/axes/XAxis.js#L45](https://github.com/apexcharts/apexcharts.js/blob/7a7f6cc1bc389c3f568fd9c47d4e9d194898f5cd/src/modules/axes/XAxis.js#L45)

**Comment by Sr-santi** [comment]
you need to specify the width and height to avoid this error:
in next.js 

```
import dynamic from "next/dynamic";
const ReactApexChart = dynamic(() => import("react-apexcharts"), {
  ssr: false,
});

const Component = () => {
    ...
    return (
    <>
        ....
        <ReactApexChart
             options={options}
             series={series}
             type="bar"
             width={widthValue}
             height={heighValue}
         />
    </>
    )
}
```
