### ISSUE TITLE
Chart goes out of the parent div

### ISSUE THREAD

**Issue by imranfakhrul** [apexcharts/react-apexcharts#48]
I'm working on an admin dashboard where I'm using `react-apexcharts`. I integrated the chart and everything works fine. But whenever the application mounts the first time or reloads, the charts behave strangely. They go (overflow) out of the parent div. I tried with some other charts but they worked fine. 
I'm using: 
`apexcharts`: `2.2.2`, 
`react-apexcharts`: `1.3.0`
`react`: `16.7.0`
OS: 
`linux 18.04.2`
![Screenshot from 2019-03-15 23-27-10](https://user-images.githubusercontent.com/29129768/54451568-4e339c00-477d-11e9-9273-fb4a09734e68.png)

**Comment by junedchhipa** [comment]
Please upgrade to `apexcharts@3.6.2` to fix this issue.

**Comment by imranfakhrul** [comment]
I tried this way, but it doesn't solve the problem. 
And even this version creates another problem for me. It gives a lot of errors which is from the library itself, not my code. 
But version 2.2.2 solved this error!

**Comment by junedchhipa** [comment]
Can you post the errors?

**Comment by junedchhipa** [comment]
Please post your full example (chart configuration) or create a codepen.
I suspect the issue is with the configuration as you are using the charts which runs fine on the website (React versions)

**Comment by imranfakhrul** [comment]
Ok, I'm sorry to say that I tried some ways with this, like creating a new project, creating a repl, and everywhere it works fine but my project. Maybe your suspension is right, the problem is in my project configuration, but I couldn't find where it is. So I decided to create a brand new project and take the code there. 
Thank you for your quick reply.
