### ISSUE TITLE
How to call dataURI?

### ISSUE THREAD

**Issue by MarkWestside** [apexcharts/react-apexcharts#49]
Hi,

I’m having some trouble to call `dataURI`. I did assign an ID, but `ApexCharts.exec('chartID', 'dataURI')` just returns undefined.

Thanks

**Comment by junedchhipa** [comment]
Thank you for reporting the issue.
I forgot to include the `dataURI` function in `exec`, sorry about that!
Will look into it soon.

**Comment by MarkWestside** [comment]
That wasn’t soon, you fixed it instantly 😅
Thank you.

**Comment by rujaraju** [comment]
Hi!

Could you please advice me on one thing: how do I access the variable ApexCharts in the first place? 

Thank you for your help!
