### ISSUE TITLE
position back is not working in annotations

### ISSUE THREAD

**Issue by iamdaniyall** [apexcharts/react-apexcharts#506]
annotations: {
                position: 'back',
                yaxis: []
            },

this is my code, I made the position "back" but its coming on my markers chart
![wb84m7ybk](https://user-images.githubusercontent.com/110219075/229690188-5b9d0f04-559c-4b4f-91f9-0c082e669ce5.png)

Note: I try to give high z index to "markers" but I did not find any option for this in doc.

**Comment by Muddabirchohan** [comment]
Same issue I've tried styling it custom as well but didn't worked
Any update

**Comment by iamdaniyall** [comment]
> Same issue I've tried styling it custom as well but didn't worked Any update

Unfortunately, Not. However, if you still want to use it, you can try lowering the opacity.

**Comment by Muddabirchohan** [comment]
> > Same issue I've tried styling it custom as well but didn't worked Any update
> 
> Unfortunately, Not. However, if you still want to use it, you can try lowering the opacity.

yeah but that won't meet the requirement as per design, i guess its a library limitation
