### ISSUE TITLE
Customize x axis label

### ISSUE THREAD

**Issue by supriya-somavnshi** [apexcharts/react-apexcharts#511]
Hi,

I am using react-apexcharts .I have daily financial data but I want show alternate month name on x axis .

 **xaxis: {
       labels: {
          show: true,
           formatter: function (val: any) {
            return dayjs(val).format("MMM");
          }
        }
}**

This code shows all month on x axis .

Please suggest me how to display alternate month name on x axis on the chart .The image has given below : 

![image](https://user-images.githubusercontent.com/73587174/232217462-92812fad-f277-456f-b53a-4ca262f71bbd.png)

Thanks
Supriya

**Comment by coder-shanks** [comment]
Could you share the codesandbox or stackblitz link showing the issue?
