### ISSUE TITLE
ApexChart Not working with NextJs 13 latest

### ISSUE THREAD

**Issue by soaphyls** [apexcharts/react-apexcharts#526]
Hi,
Can you check why apexchart throws multiple errors with nextJs 13.
Server Error
ReferenceError: window is not defined
This error happened while generating the page. Any console logs will be displayed in the terminal window.
even after using 
import dynamic from 'next/dynamic'
    
const Chart = dynamic(() => import('react-apexcharts'), { ssr: false });

**Comment by justdvl** [comment]
Is there a better/nicer solution than adding another component and doing props drilling?

**Comment by mvandergrift** [comment]
I'm not sure this any nicer, but it keeps things in a single component:

````js
  const [ReactApexChart, setChart] = useState(null);

  useEffect(() => {
    if (typeof window !== "undefined") {
      setChart(() => require("react-apexcharts").default);
    }
  }, []);

  return ReactApexChart && <ReactApexChart  />;
};
````
Since Next 13.5, I have not been able to get the dynamic parent/standard child import process to work reliably, but the above code works fine.

**Comment by Riyad139** [comment]
@mvandergrift 
``` ts
import dynamic from 'next/dynamic';
const Chart = dynamic(() => import('react-apexcharts'), {
  ssr: false,
});
```
This should be a better way

**Comment by Dmarcotrigiano** [comment]
> Instead of importing react-apexcharts dynamically, create a component and import react-apexcharts normally in that component then import that component dynamically into your parent component. Here's an example of how it should look like
> 
> Parent.tsx
> 
> ```
> import dynamic from "next/dynamic";
> 
> const DynamicGraph = dynamic(() => import("@/components/Child"), {
>   ssr: false,
> });
> 
> const Parent = () => {
>     return <><DynamicGraph /></>
> }
> 
> export default Parent;
> ```
> 
> Child.tsx
> 
> ```
> import Chart from "react-apexcharts";
> 
> const Child = () => {
>      return <><Chart options={options} series={series} /></>
> }
> 
> export default Child;
> ```

Dynamically importing the charts alone was not the solution. This was the solution, what a pain.

**Comment by longlostnick** [comment]
React.lazy works for me:

```typescript
export const ApexChart = lazy(() => import('react-apexcharts'));
```
