### ISSUE TITLE
No default export found in imported module "react-apexcharts" 

### ISSUE THREAD

**Issue by vaynevayne** [apexcharts/react-apexcharts#541]
<img width="874" alt="image" src="https://github.com/apexcharts/react-apexcharts/assets/124666577/64d8eaff-ca40-4999-9e22-427120390b68">

**Comment by raphaelandradezup** [comment]
I have found a solution that's ok to keep the lib updated. Adding to eslint configuration file the following code will ensure that the default import will not break.
```
"settings": {
    //...others settings
    "import/ignore": [
      "react-apexcharts"
    ],
 }
```

**Comment by vaynevayne** [comment]
> What is the principle behind this?

**Comment by yairEO** [comment]
why is this closed? this is a real issue
