### ISSUE TITLE
3D charts/graph

### ISSUE THREAD

**Issue by Abhishek-Kumbhani** [apexcharts/react-apexcharts#565]
I would love to have something like 3d graphs and charts, 
for references google's 3d pie chart.
![Screenshot 2023-12-14 142956](https://github.com/apexcharts/react-apexcharts/assets/124597949/e30ab141-3e06-42c4-aa66-9ec8b9086eec)

**Comment by junedchhipa** [comment]
Sorry, this is not planned and is not in the roadmap.
