### ISSUE TITLE
Multiple TypeErrors when deselecting all legend options on a Line Chart

### ISSUE THREAD

**Issue by TRWGali** [apexcharts/react-apexcharts#57]
Deselecting all legend options results in:
![Capture](https://user-images.githubusercontent.com/34773851/55911935-a6f52980-5baf-11e9-8cb0-3a1a08ec9f79.PNG)

Trying to re-select the deselected options:
![Capture](https://user-images.githubusercontent.com/34773851/55912170-28e55280-5bb0-11e9-9e56-57b2d24a5bef.PNG)

sandbox - https://codesandbox.io/s/6v71p3y9l3

**Comment by junedchhipa** [comment]
@TRWGali Sorry for the delayed response.
I just checked out the codesandbox demo in latest version `apexcharts@3.6.10` and this doesn't happen. Can you confirm if it works fine in the current version?
I will re-open the issue again if the bug still exists.
