### ISSUE TITLE
Bar Chart Left to right swoop in animation

### ISSUE THREAD

**Issue by TomerLankri** [apexcharts/react-apexcharts#572]
I am not able to disable the swoop in left to right animation on multiple bar chart.
I want only the growing (Down to up) animation and disable the swoop in left to right .

https://github.com/apexcharts/react-apexcharts/assets/39373833/a53b55ac-7530-4fde-ac5a-b89fa440d355

**Comment by junedchhipa** [comment]
```js
chart: {
  animations: {
    animateGradually: {
      enabled: false
    }
  }
}
```

**Comment by TomerLankri** [comment]
Did not solve the issue

**Comment by sonjajonsd** [comment]
I have the same issue, it would be nice to be able to control the animation a bit more. I also only want it to grow and not "swoop in". 

Your solution to disable "animateGradually" does not solve the issue.
