### ISSUE TITLE
apexcharts/dist/apexcharts.common not found

### ISSUE THREAD

**Issue by ramigg** [apexcharts/react-apexcharts#59]
there is a require to apexcharts/dist/apexcharts.common which doesn't exist

**Comment by junedchhipa** [comment]
It does exist - https://cdn.jsdelivr.net/npm/apexcharts/dist/apexcharts.common.js
Please update to `apexcharts@3.6.7` to get it

**Comment by junedchhipa** [comment]
Closing as no response

**Comment by Shibbler** [comment]
I also got this error, and I have updated (at least to what I believed was correct using npm updater in my directory). Is there another way I could fix? Perhaps by adding in the raw file you linked to somewhere else?

**Comment by zocheyado** [comment]
Just ran into this on my system as well. Updating to 3.6.7 does fix the issue, but shouldn't this be a dependency of 1.3.x? Was using 1.2.x react-apexcharts and 1.5.x of apex charts and 1.3.3 update broke my project.

**Comment by junedchhipa** [comment]
`apexcharts` is a peerDependency of the latest`react-apexcharts@1.3.3`, so changing versions of `react-apexcharts` shouldn't be a problem as peerDependencies has to be installed manually. In case you were using an older version of `react-apexcharts` which had a direct dependency of `apexcharts`, then you might get the above issue.

Hope, this answers the question.

**Comment by GraphChat** [comment]
Ran into the same issue. How do I fix it?

**Comment by junedchhipa** [comment]
@GraphChat Which versions of `apexcharts` & `react-apexcharts` are you using?

**Comment by ThinkSimple** [comment]
Im getting the same error, these are the dependencies Im using:
`
 "dependencies": {
    "apexcharts": "^3.19.3",
    "next": "^9.4.4",
    "react": "^16.13.1"
,
    "react-dom": "^16.13.1",
    "react-icons": "^3.10.0"
  },`

**Comment by pablojr17** [comment]
I'm also having this problem
./node_modules/react-apexcharts/dist/react-apexcharts.min.js

The version
    "apexcharts": "^3.22.2",
    "react-apexcharts": "^1.3.7",

**Comment by kanchankk11** [comment]
npm install --save react-apexcharts apexcharts

My problem gets solved by this
