### ISSUE TITLE
Series stroke line disappearing when first value is null

### ISSUE THREAD

**Issue by arseniymlp** [apexcharts/react-apexcharts#591]
When 
1. The `xaxis` has `type: 'datetime'`,
2. There are two series with y values for the same set of same x values,
3. There is only one yaxis,
4. The second series has `type: 'line'`, and
5. The second series' earliest y value (ie the y value for the earliest x value) is `null`,

The stroke line of the second series disappears. If I change the second series to have `type: area` you can see the area is shaded but the stroke is missing.

Not sure if this is specific to react wrapper or apexcharts.js. We worked around using something [like this](https://github.com/apexcharts/apexcharts.js/issues/420#issuecomment-2019259920) by creating a custom tooltip shared tooltip and not having `null` values. But it's a really unpleasant workaround and it feels like it'll be a simple bug to fix.

**Comment by osunaintarcon** [comment]
Hello everyone!
Currently I have detected the same error when trying to display null values.
I am keeping an eye out for possible solutions.

**Comment by junedchhipa** [comment]
The original issue is not reproducible as tested on the latest version of `apexcharts@4.3.0`
