### ISSUE TITLE
Line chart redraws from scratch on updateSeries

### ISSUE THREAD

**Issue by antegulin** [apexcharts/react-apexcharts#61]
data contains multiple series:
```
[
{name: 'foo', data: [{x,y}] }
{name: 'bar', data: [{x,y}] }
...
]
```

Data of each series get periodically appended with a new value and then the `updateSeries` is called:
```js
ApexCharts.exec('realtime', 'updateSeries', data)
```
I'd like to chart to animate from existing paths, not re-draw from scratch each time.
What am I doing wrong here?

https://i.gyazo.com/451436f7dd1094023d80389446dc6611.mp4

**Comment by junedchhipa** [comment]
You have to pass the whole series array in the `ApexCharts.exec('realtime', 'updateSeries', data)` line, not just data.
Please show your full code on codesandbox so I can take a closer look.

**Comment by junedchhipa** [comment]
Closing due to lack of response.
Feel free to re-open if the issue still persists in a standalone codesandbox example.
