### ISSUE TITLE
Uncaught (in promise) TypeError: can't access property "show", i is undefined

### ISSUE THREAD

**Issue by NRevillet** [apexcharts/react-apexcharts#619]
Hello everyone,
I've got this error in my project when trying to add annotations to my chart.
There is 4 charts on the page using the same template, and adding this code (test code from the official documentation):

`      annotations: { 
        yaxis: [
          {
            y: 8800,
            borderColor: '#00E396',
            label: {
              borderColor: '#00E396',
              style: {
                color: '#fff',
                background: '#00E396'
              },
              text: 'Y-axis annotation on 8800'
            }
          }
        ]
      },`

 to the apex-chart causes the following crash on save :

![image](https://github.com/user-attachments/assets/751f6339-a5a8-4fd0-8016-04b5f96a6f37)

and after this error, removing the code and saving makes react reload the page, but keeps throwing this error, but it goes away with a manual reload of the browser (this issue might be unrelated idk).

From what i've searched, this issue might be related to : https://github.com/apexcharts/react-apexcharts/issues/598
Thank you for any help you might provide 😄

**Comment by kiplrohit** [comment]
+1

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'show')
    at t.value (apexcharts.common.js:6:1)
    at apexcharts.common.js:6:1
    at Array.forEach (<anonymous>)
    at t.value (apexcharts.common.js:6:1)
    at t.value (apexcharts.common.js:6:1)
    at apexcharts.common.js:14:1
    at new Promise (<anonymous>)
    at t.value (apexcharts.common.js:14:1)
    at apexcharts.common.js:14:1
    at new Promise (<anonymous>)
