### ISSUE TITLE
Reactivity Bug: Does not always update when there is a change to the series

### ISSUE THREAD

**Issue by svonderohe** [apexcharts/react-apexcharts#627]
I encountered a bug where the graph sometimes does not update when `series.hidden` is updated

The graph sometimes updates and sometime does not (I think this is due to the conditional logic in the `componentDidUpdate` method)

I have a fix coming in a PR

**Comment by junedchhipa** [comment]
Fixed with this [commit](https://github.com/apexcharts/apexcharts.js/commit/d3f0233179c3f9fae1e5015f97e6f4c46cf480c3)
