### ISSUE TITLE
Minimap does not work as showcased in example

### ISSUE THREAD

**Issue by rasmusgadensgaard** [apexcharts/react-apexcharts#64]
I'm trying to achieve what is shown here:

https://apexcharts.com/react-chart-demos/line-charts/brush-chart/

Specifically this minimap if the number of datapoints is high:

![image](https://user-images.githubusercontent.com/8522161/56791439-5adcf280-6807-11e9-8763-1dd6b30065d7.png)

However when I implement this example, I just get two full charts, a linechart and a area chart: 

https://codesandbox.io/s/vn50ljz613

**Comment by junedchhipa** [comment]
Updated `apexcharts@3.6.8` and `react-apexcharts@1.3.3` in the same codesandbox example and it seems to be working fine :)
https://codesandbox.io/s/q8o7zqw7lw
