### ISSUE TITLE
Animations don't work and many errors appear when changing routers.

### ISSUE THREAD

**Issue by mtr1990** [apexcharts/react-apexcharts#645]
The problem appears from version 1.4.1 and above. Thanks!

https://github.com/user-attachments/assets/4fe04c3d-2389-47d9-bd76-c9448d431895

**Comment by 2803media** [comment]
same problem with 1.5.0

**Comment by junedchhipa** [comment]
I have fixed this issue in this [commit](https://github.com/apexcharts/apexcharts.js/commit/5c3bba02849982cdcc5ec236ead609b50b593ae2).
With the next core ApexCharts release (v.4.0.1), this should be resolved.

**Comment by mtr1990** [comment]
Thank you for your hard work.

I just updated it.

```tsx
"react-apexcharts": "^1.6.0",  
"apexcharts": "^4.0.0",
```

The errors have disappeared. But the animation doesn't work
