### ISSUE TITLE
How to remove props in DOM

### ISSUE THREAD

**Issue by mtr1990** [apexcharts/react-apexcharts#647]
We can remove these props in the DOM after rendering? `type`, `series`,`options`. Thanks!

```tsx
<div type="line" series="[object Object]" options="[object Object]" width="100%" height="100%" class="" style="min-height: unset;">
.....
</div>
```

**Comment by junedchhipa** [comment]
This was an issue in older versions.
Can you specify which version of `apexcharts` and `react-apexcharts` are you using?
