### ISSUE TITLE
 long time for completing the drawing of the screen

### ISSUE THREAD

**Issue by ssswhite007** [apexcharts/react-apexcharts#660]
I am trying to display the bar chart using react-apexcharts in React.js.

`import React, { useEffect, useState } from 'react';
import { FormControl, Grid, InputLabel, MenuItem, Select, TextField, Typography } from '@mui/material';
import { toast } from 'react-toastify';
import Chart from 'react-apexcharts';
import moment from 'moment';
import { useTheme } from '@mui/material/styles';
import LoadingButton from '@mui/lab/LoadingButton';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
import MainCard from 'components/Cards/MainCard';
import SubCard from 'components/Cards/SubCard';
import ReportFileExports from 'components/Reports/FileExports';
import ApiHelper from 'utils/apiHelper';
import { gridSpacing, dateRangeOptions, timeIntervalDateRanges, API_URL } from 'utils/constants';
import { handleUpdateReportDateRange, convertDate, validateCustomDateRange } from 'utils/commonHelpers';

const ReportsPowerState = () => {
    const theme = useTheme();
    const [loading, setLoading] = useState(false);
    const currentDate = new Date();
    const today = new Date();
    const [startDate, setStartDate] = useState(currentDate.setMonth(currentDate.getMonth() - 1));
    const [endDate, setEndDate] = useState(today.setDate(today.getDate() - 1));
    const [dateRangeValue, setDateRangeValue] = useState('1month');
    const [timeInterval, setTimeInterval] = useState('day');
    const [groupId, setGroupId] = useState(0);
    const [policyId, setPolicyId] = useState(0);
    const [deviceTypeId, setDeviceTypeId] = useState(0);
    const [groupsData, setGroupsData] = useState([]);
    const [policiesData, setPoliciesData] = useState([]);
    const [deviceTypesData, setDeviceTypesData] = useState([]);
    const [powerStatesData, setPowerStatesData] = useState(initialState);
    const [filtersData, setFiltersData] = useState([]);

    useEffect(() => {
        getGroups();
        getPolicies();
        getDeviceTypes();
    }, []);

    const getGroups = () => {
        ApiHelper.get('/api/reports/groups/')
            .then((res) => {
                setGroupsData(res.data);
            })
            .catch();
    };

    const getPolicies = () => {
        ApiHelper.get(API_URL.MANAGEMENT_POLICY)
            .then((res) => {
                setPoliciesData(res.data);
            })
            .catch();
    };

    const getDeviceTypes = () => {
        ApiHelper.get('/api/reports/device_types/')
            .then((res) => {
                setDeviceTypesData(res.data);
            })
            .catch();
    };

    const handleChangeDateRangeValue = (e) => {
        const value = e.target.value;
        console.log(value);
        setDateRangeValue(value);
        const updatedStartDate = handleUpdateReportDateRange(value);
        setStartDate(updatedStartDate);
    };

    const getPowerStateData = () => {
        if (convertDate(startDate) === 'Invalid date') {
            toast.error('Fail! The start date format is incorrect');
            return true;
        }
        if (convertDate(endDate) === 'Invalid date') {
            toast.error('Fail! The end date format is incorrect');
            return true;
        }
        if (moment(convertDate(startDate)) > moment(convertDate(endDate))) {
            toast.error('Fail! The start date can not be greater than the end date');
            return true;
        }

        if (dateRangeValue === '0') {
            const validation = validateCustomDateRange(startDate, endDate, timeInterval);
            if (!validation.isValid) {
                toast.error(`Fail! ${validation.message}`);
                return true;
            }
        }
        setLoading(true);
        ApiHelper.post('/api/reports/power_state/', {
            start_date: convertDate(startDate),
            end_date: convertDate(endDate),
            time_interval: timeInterval,
            device_type_id: deviceTypeId === 0 ? '' : deviceTypeId.toString(),
            group_id: groupId === 0 ? '' : groupId.toString(),
            policy_id: policyId === 0 ? '' : policyId.toString()
        })
            .then((res) => {
                console.log(res.data);
                setPowerStatesData(res.data);
                setLoading(false);
                toast.success('Successfully done');
            })
            .catch(() => {
                setPowerStatesData(initialState);
                setLoading(false);
                toast.warning('There is no power state data');
            });
    };

    const handleTimeIntervalChange = (e) => {
        const newInterval = e.target.value;
        console.log(newInterval);
        setTimeInterval(newInterval);

        const availableRanges = timeIntervalDateRanges[newInterval];
        setDateRangeValue(availableRanges[0].value);
        const updatedStartDate = handleUpdateReportDateRange(availableRanges[0].value);
        setStartDate(updatedStartDate);
    };

    const series = [
        {
            name: 'User Active',
            data: powerStatesData.user_active
        },
        {
            name: 'All On',
            data: powerStatesData.all_on
        },
        {
            name: 'CPU On',
            data: powerStatesData.cpu_on
        },
        {
            name: 'All Sleep',
            data: powerStatesData.all_asleep
        },
        {
            name: 'All Off',
            data: powerStatesData.all_off
        },
        {
            name: 'Unknown',
            data: powerStatesData.unknown
        }
    ];
    const options = {
        colors: ['#045DFB', '#FB041F', '#F4FB04', '#03F948', '#036705', '#ffffff'],
        chart: {
            stacked: true,
            toolbar: {
                show: false
            }
        },
        xaxis: {
            categories: powerStatesData.dates,
            title: {
                text: 'Date'
            }
        },
        yaxis: {
            title: {
                text: '% of Day'
            }
        },
        dataLabels: {
            enabled: false
        }
    };

    const getHelperText = (timeInterval) => {
        switch (timeInterval) {
            case 'hour':
                return '2 weeks';
            case 'day':
                return '3 months';
            case 'week':
                return '6 months';
            case 'month':
                return '1 year';
            default:
                return '';
        }
    };

    return (
        <MainCard title="Activity Reports Management" cardHeaderTitle="Power State and Activity Report" cardHeaderShow={true}>
            <Grid container spacing={gridSpacing}>
                <Grid item xs={10}>
                    <Typography sx={{ fontSize: '16px' }}>
                        Provides a stacked barchart showing the various interactions of CPU and display state with user activity
                    </Typography>
                </Grid>
                <Grid item xs={3}>
                    ...
                </Grid>
                <Grid item xs={9}>
                    {loading === true ? (
                        <Typography sx={{ mt: 3, textAlign: 'center', fontSize: '16px', fontWeight: 'bold' }}>
                            Please wait... This may take some time...
                        </Typography>
                    ) : powerStatesData.dates.length === 0 ? (
                        <Typography sx={{ textAlign: 'center', mt: 3 }} color={theme.palette.secondary.main}>
                            No data for the power state report
                        </Typography>
                    ) : (
                        <Chart id="powerState" options={options} series={series} type="bar" width="80%" />
                    )}
                </Grid>
            </Grid>
        </MainCard>
    );
};

export default ReportsPowerState;
`
This is my full code for displaying the chart.
powerStatesData is about 700 data points from the backend.
It took a long time to draw this.
Do you know how I can draw quickly?

Please help me!

**Comment by junedchhipa** [comment]
Please provide a codesandbox to reproduce easily.
