### ISSUE TITLE
Not shared tooltips don't work

### ISSUE THREAD

**Issue by mitom** [apexcharts/react-apexcharts#68]
When setting tooltips explicitly to not be shared, tooltips just no longer show up at all.
To demonstrate: https://codesandbox.io/s/ze7g2

I've also tried setting `intersect` to see if it helps, but it doesn't seem to make any difference. Any ideas?

**Comment by speedyankur** [comment]
It is working fine as expected.

Actually, you did a small mistake while defining your series, There is no need to define TYPE for your series.

https://codesandbox.io/embed/react-basic-example-ul10p

**Comment by mitom** [comment]
Thank you for the response. You are correct it does work in the scenario where there are only line types involved. The reason why in my example `type` was defined was because they are generated and can be mixed types.

I took the mixed type example from the docs and tried if it still works:
https://codesandbox.io/s/react-basic-example-xmhni

It has tooltips for the columns, but doesn't for either area or line. Removing the `type` from the line doesn't make a difference either.
