### ISSUE TITLE
Using custom legend to toggleSeries in a React app 

### ISSUE THREAD

**Issue by Amber-Williams** [apexcharts/react-apexcharts#73]
Using the import Chart  from 'react-apexcharts'; method to generate a Chart 
 `<Chart
options={this.state.options}
series={this.state.series}
type="line"
/>`

There doesn't seem to be away to use ApexCharts.toggleSeries to toggle a series line with react-apexcharts

**Comment by Amber-Williams** [comment]
Figured out the solution and thought I would post it since here for anyone else

```
import Chart  from 'react-apexcharts';
import ApexCharts from 'apexcharts';

toggle (e) {
  ApexCharts.exec('graphID', 'toggleSeries', e.target.value);
}

render() {
  <>
    <button value="seriesNameHere1" onClick={this.toggle}>Series 1</button>
    <button value="seriesNameHere2" onClick={this.toggle}>Series 2</button>
    <Chart
      options={this.state.options}
      series={this.state.series}
      type="line"
    />
  </>
}
```

**Comment by rhaicode** [comment]
If you don't want to rely on a click event, you can also set it on `componentDidMount`

Here is an example

`
import Chart  from 'react-apexcharts';
import ApexCharts from 'apexcharts';
`

`
constructor(props) {
  this.state = {
    options: {...},
    series: [
       { name: 'Pending', data: [...] },
       { name: 'Failed Bid', data: [...] },
       { name: 'Delivered', data: [...] },
    ],
    style: {...}
  }
}

// We have 'toggled' the Failed Bid and Delivered,  now the chart is only showing data related to Pending 
componentDidMount() {
  Chart.exec("frequencyReport", "toggleSeries", "Failed Bid");
  Chart.exec("frequencyReport", "toggleSeries", "Delivered");
}


render() {
    <ApexCharts
          options={this.state.options}
          series={this.state.series}
          style={this.state.style}
          type="line"
        />
}

`

**Comment by dandymon** [comment]
Perfect, thanks Amber
My only addition is (because it's not very obvious) that the chart id is not a prop in the Chart tag (or wasn't for me at least). 
chart `id` can be set in options

````
const chartOptions={
   chart:{
      id:"chartId123",
      type:"...",
      ...
   }
   ...
}

**Comment by mtr1990** [comment]
@Amber-Williams Thanks for help, Have example for hover Item ?

**Comment by butslof** [comment]
Perfeita solução

**Comment by KostiantynFilipenkov** [comment]
> @Amber-Williams Thanks for help, Have example for hover Item ?

Hello! Did you find a solution? How to call hover?

**Comment by chetan-187** [comment]
Can anyone send me an example of how to implement this?

**Comment by ahmadertarizqi** [comment]
Hello @Amber-Williams, when import ApexCharts (not ReactApexcharts) for exec method. I get an error ```windows is not defined``` on NextJS 13.

Can anyone help this? I've tried using ```dynamic import``` from NextJS, but it still doesn't work

**Comment by piyawatpm** [comment]
Hi @ahmadertarizqi, I had the same problem and my solution is i use normal import for the CustomChart component that render the Chart and use **dynamic import** when import the CustomChart component. Hope it helps
