### ISSUE TITLE
Sync behavior in brush charts

### ISSUE THREAD

**Issue by dnlprplt** [apexcharts/react-apexcharts#79]
Hi,

When having a brush chart with a target chart, and having different options under the yaxis property, I am experiencing a behavior that I didn't expect.

When you select an area in the brush chart (second one), the number of ticks of the y axis is modified in the target chart (first one) to match the brush chart.

When you then select an area in the target chart, the number of ticks is changed back to what it was.

This also happens when you want to hide the y axis labels in one chart and not the other one.

I've create a reproducible example here: https://codesandbox.io/s/react-basic-example-tp1in

This might also be linked to https://github.com/apexcharts/react-apexcharts/issues/31

**Comment by lauraalkhoury-youitv** [comment]
Seeing this issue too

**Comment by lauraalkhoury-youitv** [comment]
Seeing this too. @junedchhipa are you guys able to take a look at this any time soon? It's blocking me from using the sync feature.
