### ISSUE TITLE
How can I set chart margin for sparkline

### ISSUE THREAD

**Issue by tawsbob** [apexcharts/react-apexcharts#8]
I'm trying to change de default "margin" ( translate(10, 10) ) of sparkline to zero but I dont found anything about on docs.

Here a example what I need to do [https://apexcharts.com/javascript-chart-demos/dashboards/modern/](https://apexcharts.com/javascript-chart-demos/dashboards/modern/)

**Comment by junedchhipa** [comment]
The grid configuration is available for axis charts (line/column/area/...) from which you can control the padding inside the chart area.

```javascript
grid: {
    padding: {
          top: 0,
          left: 0,
          right: 0,
          bottom: 0
     }
}
```

https://apexcharts.com/docs/options/grid/#padding

**Comment by junedchhipa** [comment]
I made the default margins for sparkline to 0 in this commit https://github.com/apexcharts/apexcharts.js/commit/5e91c3935e1f25fd24495bc90b0f219e30a06bf0

Thanks for reporting

**Comment by tawsbob** [comment]
Thanks man!!!!!!!!!!!!!!!!!!
