### ISSUE TITLE
Animation on pie/donut breaks if series contains a 0 value

### ISSUE THREAD

**Issue by nabeelmehmood** [apexcharts/react-apexcharts#80]
I'm running into an issue working with a project with dependencies:
"apexcharts": "^3.8.5",
"react-apexcharts": "^1.3.3",

Sending a value of 0 in a series, e.g [0,1,3,2], results in the initial animation of the pie/donut chart to fail and the chart appears instantly. I haven't tested this on other chart types.

**Comment by junedchhipa** [comment]
This is fixed in the latest release of apexcharts
