### ISSUE TITLE
Update Series

### ISSUE THREAD

**Issue by ThinkSalat** [apexcharts/react-apexcharts#85]
Hi,

There are methods for updating the series [here](https://apexcharts.com/docs/methods/#updateSeries) and [here](https://apexcharts.com/react-chart-demos/line-charts/realtime/) they show an example by using ApexCharts.exec(id, method, etc)

how do I import the ApexCharts thing? How do I do this? The docs have nothing about this and they're really disorganized.

**Comment by junedchhipa** [comment]
import ApexCharts from 'apexcharts'.

OR
If you are importing ApexCharts by script
```
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
```
then you don't need to do anything. You can directly use the global ApexCharts variable.

**Comment by ThinkSalat** [comment]
Wow, thank you so much! I highly suggest adding this somewhere in the documentation. I had NO idea how to do this!
