### ISSUE TITLE
Unable to override default args when updating options

### ISSUE THREAD

**Issue by kevinehosford** [apexcharts/react-apexcharts#86]
Thanks for the great work!

I notice when updating a chart with new options, the `react-apexcharts` props don't allow for passing additional arguments to the update options function. Is that intentional or could the API be expanded to allow for customizing that function call?

Example arguments one might want to specify:
https://apexcharts.com/docs/methods/#updateOptions e.g. `animate` or `updateSyncedCharts`.

Lines of code highlighting how this is not possible:
https://github.com/apexcharts/react-apexcharts/blob/master/src/react-apexcharts.jsx#L117

**Comment by jsmccrumb** [comment]
That line of code...
```
} else {
        // both might be changed
        this.chart.updateOptions(this.getConfig())
}
```
if both might have changed shouldn't it call both update series and update options?
