### ISSUE TITLE
Solid border type of annotation doesn't work

### ISSUE THREAD

**Issue by pnemi** [apexcharts/react-apexcharts#9]
Hey,

when I set `options.annotations.xaxis` borderType to solid (should be default tho) it's still dashed.

**Comment by junedchhipa** [comment]
The doc is wrong for annotations, thanks for reporting.

Try `strokeDashArray = 0` instead of `borderType`

Note: `strokeDashArray` accepts a number value

**Comment by junedchhipa** [comment]
Updated the docs
https://apexcharts.com/docs/options/annotations/
