### ISSUE TITLE
How to update chart options in react?

### ISSUE THREAD

**Issue by nbarman760** [apexcharts/react-apexcharts#90]
I am unable to update already rendered chart options. I am using react.
Please help. How can I call update option function.

**Comment by matttk** [comment]
Can you give some more information? I just feed the options into the `options` prop for `ReactApexChart` in the render function and the chart updates.

**Comment by junedchhipa** [comment]
@nbarman760 Have a look at this [codesandbox](https://codesandbox.io/s/mzzq3yqjqj) to see how to update the chart.

Also, in the README - https://github.com/apexcharts/react-apexcharts#how-do-i-update-the-chart

### How do I update the chart?
Just change the series or any option and it will automatically re-render the chart.

Important: While updating the options, make sure to update the outermost property even when you need to update the nested property.

✅ Do this
```
this.setState({
  options: {
    ...this.state.options,
    xaxis: {
      ...this.state.options.xaxis,
      categories: ['X1', 'X2', 'X3']
    }
  }
})
```

❌ Not this
```
this.setState({
  options.xaxis.categories: ['X1', 'X2', 'X3']
})
```

**Comment by mkgareja** [comment]
Thanks a lot @junedchhipa

**Comment by Andynopol** [comment]
The problem with this is that the chart will rerender every time you change something. So let's say you add a toggle for datalabels. and you have zoom on. How do you enable datalabels without the zoom to refresh?

If you use the state method, the entire chart will re-render.

**Comment by KaungHtet-Naing** [comment]
I'm encountering an issue where I am unable to dynamically update the x-axis categories. Does anyone have a solution or suggestions?


### Here is my code
`const options = {
  ...options
  xaxis: {
    labels: {
      show: true,
      style: {
        fontFamily: 'Supreme',
        cssClass: 'body-l',
      },
    },
    categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan'],
    axisTicks: {
      show: false,
    },
    axisBorder: {
      show: false,
    },
  },
};

const CustomChart = ({ data, year }) => {
  const myDivRef = useRef<HTMLDivElement>(null);
  const [chartOptions, setChartOptions] = useState<any>(options);

  useEffect(() => {
    setChartOptions((prevOptions) => ({
      ...prevOptions,
      xaxis: {
        ...prevOptions.xaxis,
        categories: [year, year, year, year, year, year, year, year, year, year, year, year],
      },
    }));
  }, [year]);

  return (
    <div className='h-full w-full overflow-x-auto ' ref={myDivRef}>
      <Chart options={chartOptions} series={data} type='bar' width={myDivRef.current?.clientWidth} height='96%' />
    </div>
  );
};

export default CustomChart;
`

### This works 
`
  useEffect(() => {
    setChartOptions((prevOptions) => ({
      ...prevOptions,
      xaxis: {
        ...prevOptions.xaxis,
categories: [
          ['Jan', '1999'],
          ['Feb', '1999'],
          ['Mar', '1999'],
          ['Apr', '1999'],
          ['May', '1999'],
          ['Jun', '1999'],
          ['Jul', '1999'],
          ['Aug', '1999'],
          ['Sep', '1999'],
          ['Oct', '1999'],
          ['Nov', '1999'],
          ['Dec', '1999'],
        ],      },
    }));
  }, [year]);
`

### This didn't
`
  useEffect(() => {
    setChartOptions((prevOptions) => ({
      ...prevOptions,
      xaxis: {
        ...prevOptions.xaxis,
        categories: [year, year, year, year, year, year, year, year, year, year, year, year],
      },
    }));
  }, [year]);

`

**Comment by KaungHtet-Naing** [comment]
I'm encountering an issue where I am unable to dynamically update the x-axis categories. Does anyone have a solution or suggestions?

### Here is my code
```
const options = {
  ...options
  xaxis: {
    labels: {
      show: true,
      style: {
        fontFamily: 'Supreme',
        cssClass: 'body-l',
      },
    },
    categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan'],
    axisTicks: {
      show: false,
    },
    axisBorder: {
      show: false,
    },
  },
};

const CustomChart = ({ data, year }) => {
  const myDivRef = useRef<HTMLDivElement>(null);
  const [chartOptions, setChartOptions] = useState<any>(options);

  useEffect(() => {
    setChartOptions((prevOptions) => ({
      ...prevOptions,
      xaxis: {
        ...prevOptions.xaxis,
        categories: [year, year, year, year, year, year, year, year, year, year, year, year],
      },
    }));
  }, [year]);

  return (
    <div className='h-full w-full overflow-x-auto ' ref={myDivRef}>
      <Chart options={chartOptions} series={data} type='bar' width={myDivRef.current?.clientWidth} height='96%' />
    </div>
  );
};

export default CustomChart;
```


### This works 
```
useEffect(() => {
    setChartOptions((prevOptions) => ({
      ...prevOptions,
      xaxis: {
        ...prevOptions.xaxis,
categories: [
          ['Jan', '1999'],
          ['Feb', '1999'],
          ['Mar', '1999'],
          ['Apr', '1999'],
          ['May', '1999'],
          ['Jun', '1999'],
          ['Jul', '1999'],
          ['Aug', '1999'],
          ['Sep', '1999'],
          ['Oct', '1999'],
          ['Nov', '1999'],
          ['Dec', '1999'],
        ],      },
    }));
  }, [year]);

```

### This didn't
```
  useEffect(() => {
    setChartOptions((prevOptions) => ({
      ...prevOptions,
      xaxis: {
        ...prevOptions.xaxis,
        categories: [year, year, year, year, year, year, year, year, year, year, year, year],
      },
    }));
  }, [year]);

```
