### ISSUE TITLE
TypeError: Cannot read property 'chart' of undefined

### ISSUE THREAD

**Issue by michaeldaineka** [apexcharts/react-apexcharts#93]
--- When it performs

When i moving to another Link from LineCharts.js page it causes errors

--- To view the blamed file (take a look at LineCharts.js)

https://codesandbox.io/s/loving-herschel-ebrzu

--- Screenshot of the error

![image](https://user-images.githubusercontent.com/43149862/66187944-acc75580-e68e-11e9-92ee-46eb9882b0ae.png)

**Comment by kmartin62** [comment]
+1

**Comment by kmartin62** [comment]
I solved this problem. Define a `_isMounted ` boolean. Set `_isMounted = true` in `componentDidMount()`, which is apart of react's lifecycle, and change its state to `false` in `componentWillUnmount()`. Wrap the body of `intervals()` function with a basic `if(_isMounted)` so it can check if the component is active or not. What `exec()` does is it creates objects all the time in the background, even when you navigate from one component to another. In this case `.exec()` can't find the predefined chart and throws an error

**Comment by michaeldaineka** [comment]
> I solved this problem. Define a `_isMounted ` boolean. Set `_isMounted = true` in `componentDidMount()`, which is apart of react's lifecycle, and change its state to `false` in `componentWillUnmount()`. Wrap the body of `intervals()` function with a basic `if(_isMounted)` so it can check if the component is active or not. What `exec()` does is it creates objects all the time in the background, even when you navigate from one component to another. In this case `.exec()` can't find the predefined chart and throws an error

Thanks for solving the problem
