### ISSUE TITLE
when using tickPlacement: 'between', the numbers in xAxis is rounded, in line chart

### ISSUE THREAD

**Issue by mkantz84** [apexcharts/react-apexcharts#95]
When using `tickPlacement: 'between'`, the xAxis category numbers is shown rounded.
with `tickPlacement: 'between'`:
![image](https://user-images.githubusercontent.com/22270407/66321443-3db95d80-e929-11e9-8aad-fe0e69af6946.png)

without:
![image](https://user-images.githubusercontent.com/22270407/66321385-22e6e900-e929-11e9-8497-4dc0808a0fc2.png)

version: ^1.3.3

Any suggestions?

**Comment by junedchhipa** [comment]
You can override such behavior by 

```javascript
xaxis: {
  type: 'numeric',
  labels: {
    formatter: function(val) {
      return val.toFixed(1)
    }
  }
}
```
