### ISSUE TITLE
Options carrying over between renders

### ISSUE THREAD

**Issue by jsmccrumb** [apexcharts/react-apexcharts#96]
If using a stacked column chart (with the default options from the example) then switch to a non-stacked bar chart, it will remain stacked. Unless you add in key specifying stacked: false (that key is NOT required initially, only after you load the stacked).

Not sure if this is intended or not - certainly is a bit surprising.

React 16.10, react-apexcharts 1.3.3, apex charts 3.8.6. Possibly something to do with how it is handling option updates?

[Code sandbox](https://codesandbox.io/s/react-update-example-hs1tl?fontsize=14)

Not sure if this is related to #16 that never got details?

**Comment by jcridev** [comment]
I see this was never answered, but I'm facing the same issue. Options clearly not getting reset.

**Comment by yohainnn** [comment]
try updating options inside useEffect. worked for me
