### ISSUE TITLE
options: specify width

### ISSUE THREAD

**Issue by jsmccrumb** [apexcharts/react-apexcharts#97]
Width option overriden with default width 100%. Would be nice to be able to use

```
const options = {
    labels: ["Team A", "Team B", "Team C", "Team D", "Team E"],
    chart: {
      width: 100
    }
}
```
to set width (understand its possible by setting width property on the component but would be nice to also be able to use the options without having a default width = 100% showing up

[Code sandbox](https://codesandbox.io/s/react-update-example-5iexi)

**Comment by chvanikoff** [comment]
Please correct me if there is a way to make charts responsive, I would be happy to be mistaken, but from what I understand, it is only possible to achieve this by being able to set width/height via options. This issue seems huge to me.
