### ISSUE TITLE
Missing Feature - How to align title to center?

### ISSUE THREAD

**Issue by Daniel4Digital** [apexcharts/react-apexcharts#99]
Hi there, after read the Docs I couldnt find any way for align the chart title to the center.

I was able to add bold to it via css:

div >>> .apexcharts-title-text {
  font-weight: 600;
}

and I was able to change some styling:

title: {
          text: "My Title",
          margin: 50,
          style: {
            fontFamily: 'Nunito',
            fontSize: '24px',
            color: 'var(--primary-active)'
          },
        },

Now I wanted to center the text to the div but it doesn't seem possible.

Any idea?

**Comment by junedchhipa** [comment]
```
options: {
  title: {
    align: 'center'
  }
}

```

https://apexcharts.com/docs/options/title/
